### ISSUE TITLE
2 color GIF > JXL lossless = color reduction

### ISSUE THREAD

**Issue by necros2k7** [libjxl/libjxl#1135]
**Describe the bug**
test gif becomes black image after conversion

**To Reproduce**
cjxl 1.gif 1.jxl -d 0.0 -e 9

**Expected behavior**
lossless convertion with no color reduction

**Screenshots**
test image 
![1](https://user-images.githubusercontent.com/16452453/151684340-f118b465-d7fa-4291-8811-825e09ba65db.gif)

**Environment**
 - OS:  Win11
 - Compiler version:  x64 ( GENERIC ) MinGW-w64 GC
 - CPU type: x64
 - cjxl/djxl version string :JPEG XL encoder v0.7.0 21da8c2 [SSE4,SSSE3,Scalar]

**Comment by TheHardew** [comment]
Are you sure that's not a problem with your viewer? Or maybe could you send the jxl file? I'm testing on linux and it works correctly.

**Comment by ziemek99** [comment]
I've just inspected the GIF in GIMP and it turns out the background is transparent.
![gimp](https://user-images.githubusercontent.com/15923635/151718098-e99baa90-d842-4f05-8f29-9f643c250a76.png)

Logging into GitHub, and thus enabling the dark theme, already revealed an issue with showing this GIF on dark backgrounds.
![github](https://user-images.githubusercontent.com/15923635/151718176-23ef4f1a-25a6-4fc3-8f6f-6df8c41fc1e5.png)

@necros2k7 Please download the PNG below, convert it to JXL and post here screenshots of your image viewer showing both original PNG and resulting JXL. They'll explain a lot.
![problem](https://kornel.ski/pl/png/problem.png)

**Comment by necros2k7** [comment]
> @necros2k7 Please download the PNG below, convert it to JXL and post here screenshots of your image viewer showing both original PNG and resulting JXL. They'll explain a lot. ![problem]
They look exactly like your picture above , png and jxl in my viewer

**Comment by ziemek99** [comment]
> They look exactly like your picture above , png and jxl in my viewer

What do you mean by "exactly"? These PNGs are transparent, so they're supposed to look differently depending on the background.

> so transparent pic on black background is not a bug?

If PNG and JXL look the same in your viewer, please send me just one screenshot of the test image (the "Trollface Internet Explorer") and that will (hopefully) be enough for me to tell you if it's a bug.

**Comment by necros2k7** [comment]
![jxl](https://user-images.githubusercontent.com/16452453/152537224-75d58562-caf4-4877-88f4-0c8a57132b0f.JPG)
![png](https://user-images.githubusercontent.com/16452453/152537237-39cd9f38-d9f1-4206-9a3f-10a0b4d7f57f.JPG)

**Comment by KoromaruKoruko** [comment]
@necros2k7 as @ziemek99 pointed out, you are encoding a transparent image. thus it simply doesn't have a background and assumes the viewers background, when displayed.
there doesn't appear to be any reduction at all, just your viewer doesn't replace the transparent pixels with a default material, thus giving the illusion of a reduction.

**Comment by ziemek99** [comment]
@necros2k7 Thanks for your screenshots. Black transparent GIF on a black background shouldn't be visible at all. You're only able to see the original image because there's probably a bug in IrfanView's GIF support (transparency is replaced by white color). JPEG XL's transparency is supported properly by IrfanView and that's why black stickman disappears on a black background (as it should). If you change background color (`Options`→`Properties/Settings...`→`Viewing`→`Main window color:`) to something brighter before opening the image, your stickman will be visible in JXL format. Please check if I'm not wrong.

**Comment by ziemek99** [comment]
@necros2k7 Any updates on that? Did this investigation solve your issue?
