### ISSUE TITLE
Constraining djxl lossy JPEG output size?

### ISSUE THREAD

**Issue by xtqfv** [libjxl/libjxl#1195]
Hi, I have noticed that sometimes the output of djxl can be as much as 50% larger than the original input JPEG. I understand that JXL is not meant to be used solely as a JPEG optimizer, but I would like to reap some of the benefits of the JXL codec back in the original JPEG domain.

Is it possible to guarantee that the output of djxl will be within some factor of the original input JPEG size? If not, how should I go about trying to make the output file as small as is reasonably possible? 

Thanks

**Comment by jonsneyers** [comment]
In my opinion, besides for lossless JPEG reconstruction, JPEG output shouldn't really be in the scope of djxl in the first place — it's not a transcoding tool, just a decoder. Transcoding to another lossy codec always introduces additional loss, which is why the default JPEG encode quality is set to a high value to avoid that. You can use e.g. `djxl -q 80` if you want to encode the JPEG at a lower quality. But what is the use case where you want to convert images to JPEG XL and then to JPEG? It doesn't really make sense to me...
