### ISSUE TITLE
Automatically increase codestream level based on basic info

### ISSUE THREAD

**Issue by thebombzen** [libjxl/libjxl#1250]
If the codestream requires a Level 10 (e.g. size too big, `modular_16bit_buffers = false`, more than 4 extra channels, etc.),  and the information that tells you this is in `JxlBasicInfo` then the library should automatically increase the codestream level to 10.

There's no particular reason that the library should fail so late in the encode process with no clear indication of why it failed. Either the encode process needs a status `JXL_ENC_INCREASE_LEVEL` which forces the user to call the codestream level increase, or, preferably, it should just do this automatically without requiring an extra API call.

One possible idea would be to have `JXL_ENC_INCREASE_LEVEL` be an event that could be subscribed to in the encode loop, so if the encoder automatically increases the codestream level, then this event will be fired as an informational message, but if the client does not need this info they can simply not subscribe to the event.

**Comment by thebombzen** [comment]
Possibly related: #1237  #1247

**Comment by jonsneyers** [comment]
I think the original idea was that there's no automatic increase of the codestream level so you cannot accidentally produce a level 10 codestream when you're attempting to produce a level 5 codestream. That is, the level that is specified (which is 5 by default) is a constraint on what the encoder is allowed to do. For some of the level constraints, this makes sense: e.g. level 5 limits how many modular transforms can be done and how deep the MA tree is, which are internal encoder decisions so having the approach that "specified level is an encoder constraint" makes sense there.

However, for most of the level constraints, the constraints are directly on image header properties, like dimensions, bit depth, number and type of extra channels. For these, it would probably make sense to automatically adjust the level.

Then there are also level constraints that can be detected only late: the pixel limit for consecutive zero-duration frames and the minimum frame duration are things that could be fine for the first N frames and then be violated.

There is an api function `JxlEncoderGetRequiredCodestreamLevel` but I'm afraid that it's kind of useless in the context of a streaming encoder: the actual required level depends on the full codestream, which is only known when it's too late. It can currently be used after setting basicinfo and extra channel info, but it can of course only return the minimum required level based on that information. So it is possible that it returns 5, but if you then proceed to add a frame with a duration of 1ms, or a frame larger than the canvas with a width of 2^19, it will still be not a valid level 5 codestream.

I propose that we deprecate that function, and follow the approach of #1247: fail early when the basicinfo or extra channel info contains things that are incompatible with the specified level, so requiring applications to specify the level in advance. Then during encoding, the level is a constraint on what the encoder is allowed to do.

I don't think a separate status or event `JXL_ENC_INCREASE_LEVEL` is needed, I think it suffices to use the generic JXL_ENC_ERROR with a suitable message printed in debug builds; see also https://github.com/libjxl/libjxl/pull/823 which could be a mechanism to get more detailed error codes also in release builds, and where we could add a JXL_ENC_ERR_LEVEL_TOO_LOW or something.

**Comment by jonsneyers** [comment]
Some more reflections:

Basically there are two ways to view level setting:
- application wants to impose a constraint on the encoder to not do things that aren't allowed by the given level
- application wants to do something and the encoder has to make sure it produces a valid file (which means signaling a correct level)

If we want to accommodate both views, then I think the best approach is to have a default level of -1 which means "let the encoder choose it based on the info that is available when it has to decide what to signal", which would make it convenient for applications with the second viewpoint, and then if the default is manually overridden by the application by calling SetCodestreamLevel, it acts according to the first viewpoint: the given level is what will be signaled, the encoder will try to restrict itself to what is allowed in that level, and it will fail if that's impossible.

In any case even with the default level of -1, the encoder can fail when level constraints are violated by application input that comes after the jxll box has already been written, e.g. when encoding an animation where the first frames satisfy the max 120 fps constraint but then the application gives frames with a duration that is too short for level 5. In cases like that, the application will have to manually set the level to 10 in the beginning. But in most cases, and in particular in the single-frame case, the default would work fine.

So I propose to deprecate GetRequiredCodestreamLevel, since it is misleading anyway (there is no way to know the required codestream level before seeing all input), and instead add a default value of -1 to the codestream level (meaning "set it as low as possible given the info available when it has to be decided") instead of defaulting to 5.

**Comment by thebombzen** [comment]
This plan makes the most sense to me, similar to how we have modular mode defaulting to "-1" which lets the encoder automatically choose between VarDCT and Modular depending on distance, but still allows the client to force modular mode if this is desired.
