### ISSUE TITLE
Possible divide by zero in DrawGaussian function of splines.cc

### ISSUE THREAD

**Issue by lovell** [libjxl/libjxl#129]
Hello, the following file, discovered via fuzz testing, causes a divide by zero when decoded using the latest code on the `main` branch.

[clusterfuzz-testcase-minimized-jpegsave_buffer_fuzzer-5146219264475136.txt](https://github.com/libjxl/libjxl/files/6622107/clusterfuzz-testcase-minimized-jpegsave_buffer_fuzzer-5146219264475136.txt)

```
/src/libjxl/lib/jxl/splines.cc:105:39: runtime error: division by zero
#0 0x14cb3e8 in jxl::N_AVX2::(anonymous namespace)::DrawGaussian(jxl::Image3<float>*, jxl::Rect const&, jxl::Rect const&, jxl::Spline::Point const&, float, float const*, float, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<float, std::__1::allocator<float> >&) libjxl/lib/jxl/splines.cc:105:39
#1 0x14c7cbf in jxl::N_AVX2::(anonymous namespace)::DrawFromPoints(jxl::Image3<float>*, jxl::Rect const&, jxl::Rect const&, jxl::Spline const&, bool, std::__1::vector<std::__1::pair<jxl::Spline::Point, float>, std::__1::allocator<std::__1::pair<jxl::Spline::Point, float> > > const&, float) libjxl/lib/jxl/splines.cc:162:5
#2 0x14c2de5 in jxl::Status jxl::Splines::Apply<true>(jxl::Image3<float>*, jxl::Rect const&, jxl::Rect const&, jxl::ColorCorrelationMap const&) const libjxl/lib/jxl/splines.cc:507:5
#3 0x1479729 in jxl::FinalizeImageRect(jxl::Image3<float>*, jxl::Rect const&, std::__1::vector<std::__1::pair<jxl::Plane<float>*, jxl::Rect>, std::__1::allocator<std::__1::pair<jxl::Plane<float>*, jxl::Rect> > > const&, jxl::PassesDecoderState*, unsigned long, jxl::ImageBundle*, jxl::Rect const&) libjxl/lib/jxl/dec_reconstruct.cc:900:5
#4 0x1481683 in operator() libjxl/lib/jxl/dec_reconstruct.cc:1160:12
```

The point of failure is:

https://github.com/libjxl/libjxl/blob/6946efdf32adfde7cb7d715ae06912da5521dac7/lib/jxl/splines.cc#L105

which appears to be due to `sigma` being calculated as zero here:

https://github.com/libjxl/libjxl/blob/6946efdf32adfde7cb7d715ae06912da5521dac7/lib/jxl/splines.cc#L160-L161

I'm happy to help fix this, but am unsure what the right approach is here. Perhaps we should avoid the `DrawGaussian` call when `sigma` is zero, or maybe this is a `JXL_FAILURE` condition?

**Comment by eustas** [comment]
Thanks. Looking into it.

**Comment by eustas** [comment]
Spec does not say a thing about how to deal with zero.
Semantically (asymptotically), we could replace this gaussian with just adding the whole value to single pixel.
@jonsneyers @veluca93 WDYT?

**Comment by jonsneyers** [comment]
Single pixel thickness (without aliasing provided by gaussian) seems sensible/natural to me, but I'd like to hear the opinion of @sboukortt too.

**Comment by veluca93** [comment]
The spec does say that a / b with b == 0 does not happen...

**Comment by eustas** [comment]
Namely: "Division by zero is undefined."

**Comment by jonsneyers** [comment]
So the result is undefined, meaning a bitstream with sigma = 0 is not valid.
Decoders have to follow the spec on valid bitstreams, and can do basically whatever they want on invalid bitstreams.

I see three 'reasonable' options:

1.  Return error (it's an invalid bitstream, so refusing to decode it is perfectly fine)
2. Silently skip sigma=0 (don't draw anything, but still decode the rest of the image, i.e. ignore the invalid part)
3. Interpret sigma=0 as the asymptotic behavior, i.e. treat it as if it were sigma=epsilon for some very small nonzero epsilon or have a special case that directly does the limit case.

What about negative sigma values btw? Does that create any problems? The spec doesn't disallow it, and I guess for the code it's fine too, but semantically it's a bit weird. Sigma is a kind of thickness; I assume negative numbers cause the color to be subtracted instead of added...

If negative values are allowed (and I don't see why not), then I think it would be good to avoid a discontinuity at 0. I'm not sure if that means option 2 or 3 is best.

**Comment by eustas** [comment]
With the change of sign of sigma the addend changes sign as well.

Negative addend sounds ok to me - e.g. black lines on white background.

Given the sign change, it is better to skip the point with sigma = 0 i.e. (2) looks the best option.

**Comment by eustas** [comment]
IIUC, the fix does not avoid division by zero: `std::isfinite(1.0f / sigma)`.
Is fuzzer still unhappy, or we could close this issue?

**Comment by lovell** [comment]
@eustas As you say there's still a /0 and the fuzzer is still reporting this. Perhaps we should also add the suggested `abs(sigma) > 0.0000001f` check to `DrawGaussian`? Happy to open a PR for this if so.

**Comment by sboukortt** [comment]
If we keep the `isfinite` check on the inverse (which I think we should), wouldn’t a strict `!= 0` check be enough?

**Comment by lovell** [comment]
The fuzzer is now happy, thanks all.
