### ISSUE TITLE
New dummy container/extension for animated or lossless compressed files

### ISSUE THREAD

**Issue by Dogway** [libjxl/libjxl#1441]
**Is your feature request related to a problem? Please describe.**
Yes, there's an usability issue by not being able to tell apart if a file is lossless or not without deep inspection with external tools.
This is problematic for example for file categorization, when you need to keep both a lossy and lossless version of the same image.
Sharing the same extension makes it further difficult to store them side to side, which can come handy for quality flicker tests.

**Describe the solution you'd like**
Without this QoL change I see it difficult to supersede other formats like PNG, TGA or TIF, despite their worse compression efficiency.

**Describe alternatives you've considered**
A container with a different extension (ie. *.jll, *.jlx) for losslessly compressed files.
Similarly a different one for GIF style animated JXL (ie. *.jxa, or *.jax)

**Additional context**
none

**Comment by TheHardew** [comment]
Relevant: https://github.com/libjxl/libjxl/issues/432

Technically you can use whatever extension you want for your own files. It's true, that most people will probably use only `*.jxl`, but then again, relying on the extension is not a good idea. I've seen pngs with worse images than jpegs in the wild. The most you can probably tell from a file, is that it is lossy if it uses DCT and might be lossless if it's modular.

If the source does not specify, the best you can do is try to run some tests, for example to see how well it compresses or try to find noise manually.

**Comment by Dogway** [comment]
Yes, that's the issue, not making it a standard means it won't be used (for the general public), also from a usability stand point.
Adding a "lossless" metadata to the container along the extension change would make it easier for mass adoption in detriment of PNG or GIF ("motion" metadata).

As for your example with bad quality PNGs, that's one of the reasons for this change. You can have a very bad quality JXL and think you used low quality settings, unless a lossless metadata or extension lets you know the input stream was already damaged to begin with, and more easily relate to the bigger size.

Without an extension change you can't do sidecar encoding.

**Comment by jonsneyers** [comment]
Filename extensions are not a reliable way to handle this - you can rename a jpeg file to .png and probably it will still work in many viewers, but it doesn't make a lossy image lossless. You can also decode a jpeg and store the result in a png. Lossless or lossy is a workflow thing, not a format or extension thing.

I suggest filing issues at the relevant file managers and other tools where you want to get an indication of the file type. You can get metadata from libjxl that will give you an indication of what might be in a jxl file: something that could be lossless, something that is lossy, something that is an ex-jpeg, something with multiple layers, something with multiple frames, etc. But fundamentally it's a workflow problem. We also don't have different filename extensions for drafts vs final versions of word files, or for versions that include comments and revision marks or that don't include those. With images it's exactly the same thing. It's not because something is a png that it is lossless: it can be a converted jpeg, a color-quantized png8, an 8-bit version of a 16-bit original, a downscaled version of s higher resolution original, a rasterized version of a vector image, a flattened version of a layered image, etc.

That said, nothing prevents you from using whatever naming convention you like, and if you want to name some images .jll and others .jxl, a jxl decoder couldn't care less. The jxl standard doesn't say anything at all about the name you should give to jxl files.

**Comment by jonsneyers** [comment]
One thing I sometimes do when making multiple jxl files from an original, is just put encode flags in the filename. E.g. starting with `input.png`, I could make files called `input.png.jxl-d0`, `input.png.jxl-d1`, `input.png.jxl-d2e8epf0`, etc.

But that's a matter of personal preference imo, if you rather call them `input-lossless.jxl`, `input-high-quality.jxl`, `input-web.jxl` or something, that's of course also fine.

I don't think there is anything to be standardized here though. How people organize and name their stuff is not really our business, imo.

**Comment by Dogway** [comment]
@jonsneyers. The feature request is not for file extension, but container+extension recommendation. 
In a way standardizing what actually defines the current workflow (PNG == lossless, TGA == lossless, TIFF == most oftenly lossless).

The reason PNG is so spread is because it's easy to correlate with that fact. And there are precedents for multi extension/container formats; APNG, MNG, JNG, MJPG.


>you can rename a jpeg file to .png and probably it will still work in many viewers, but it doesn't make a lossy image lossless

"lossless" doesn't define the nature of the image (_what is lossless anyway_), but as you suggested a workflow thing. **If you losslessly encode a lossy image then that image file is lossless (as in losslessly encoded). This happens every day with lossless intermediary files in images, video and audio. And in all circumstances the cut of "lossy" and "lossless" is very clear from a container+extension stand point**; stills (bmp, png, tga, tiff), audio (wav, flac), video (lagarith, UTvideo, FFV1). In all these cases you can sidecar the lossless file to the lossy one for workflow purposes (proxys, flicker tests, etc).

You can file a feature request to Microsoft to support metadata support for JXL in Windows 11, but it won't fix the aforementioned workflow issues.

I think it's going to create a lot of confussion and lossless mode won't be used as much, but time will tell.

Thanks anyway.

**Comment by jonsneyers** [comment]
I don't see what you want us to do. What is stopping you from calling your lossless files .jll and your lossy ones .jxl, like you can call animated pngs .apng and non-animated ones .png?

Libjxl in no way forces you to use some specific extension. In fact it doesn't even have any idea what filename you are using - the api is memory-based, not file-based. Do you want to change that somehow?

**Comment by Dogway** [comment]
Then why all the fuss with the .jxl extension and not simply .jpg? Since the api is memory-based.

**Comment by monad0** [comment]
> Then why all the fuss with the .jxl extension and not simply .jpg? Since the api is memory-based.

It's just convention. If .jpg achieves the level of clarity you're looking for, go for it. I do anticipate cases where .jpg will be convenient for software interfacing outside libjxl (e.g. compressing some software's files without rewriting hard-coded filenames). For human interfacing, I'd only include it as .jpg.jxl for recompressed JPEGs.

**Comment by gitoss** [comment]
> I don't see what you want us to do. What is stopping you from calling your lossless files .jll and your lossy ones .jxl, like you can call animated pngs .apng and non-animated ones .png?

Sure, but any OS I use (Windows, Android) relies on file extension for handling - i.e. new extensions either have to be registered (Windows) or you're out of luck without re-compiling your OS (Android). Alas, it was different with AmigaOS back in the day.

That's why a binary minimum metadata lossy/lossless would be useful.
