### ISSUE TITLE
Progressive reencoding #cjxl

### ISSUE THREAD

**Issue by Sur3** [libjxl/libjxl#1615]
I tried to reencode a JPEG XL image to a progressive JPEG XL image, but it seems cjxl is not accepting JPEG XL as input.
I thought when using JPEG XL as input already the reencoding could maybe benefit from the encoded information already available..? Also the parallelization seems to be poor when encoding (only using 1-2 cores most of the time..)

**Comment by mo271** [comment]
Thanks for the reports, @Sur3!

- See #430 for the "cjxl accepting jxl files" request

- Perhaps for the "parallelization seems to be poor" it might make sense to open a separate issue with more detail around observed and expected behavior, ideally with some example files in order to investigate this.

**Comment by Sur3** [comment]
Ah ok sry I didn't find #430 prior to creating this issue because the cjxl tag is missing there.

**Comment by mo271** [comment]
> Ah ok sry I didn't find #430 prior to creating this issue because the cjxl tag is missing there.

added some labels...
