### ISSUE TITLE
Problem with creating photos

### ISSUE THREAD

**Issue by Jamaika1** [libjxl/libjxl#1643]
GCC 11.3.1 20220429
libjxl version 0.7.0-c2548a1
cjxl.exe image_21447_24bit.png image_21447_24bit.jxl -v -m -q 100 -s 5 -C 1 --num_threads=4
`Invalid flag, -q must be 0 or 1`

**Comment by mo271** [comment]
Thanks for the report! We should fix that. 
Meanwhile you can try using `-d 0` instead of `-q 100`. In theory these two should do the same (only that `-q` apparently fails currently).

**Comment by mo271** [comment]
Looking into this again, this is actually expected behavior after https://github.com/libjxl/libjxl/pull/1619.

What happened is that the argument `-m` now needs an argument, which should be either "0"  or "1".
The error message tells you that it tried to parse `-q` as and argument for `-m`.
Also the `-s` parameter is not available any more, equivalently you can use `-e` for `effort`. Notice that a speed `x` is mapped to an error `10 - x`. For you settings it happens that both speed and effort are `5`.
So I assume the following command should work for you:

```
cjxl.exe image_21447_24bit.png image_21447_24bit.jxl-v -m 1 -q 100 -e 5 -C 1 --num_threads=4
```
Please re-open the issue if there is still a problem.

**Comment by Jamaika1** [comment]
This is maybe some new version libjxl since functions have changed.
