### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by necros2k7** [libjxl/libjxl#1728]
[Z:/libjxl-main/lib/extras/enc/jpg.cc:169] (performance) Parameter 'exif' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/libjxl-main/plugins/gimp/file-jxl-save.cc:604] (performance) Parameter 'model' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/libjxl-main/tools/benchmark/benchmark_codec_jpeg.cc:51] (performance) When an object of a class is created, the constructors of all member variables are called consecutively in the order the variables are declared, even if you don't explicitly write them to the initialization list. You could avoid assigning 'jpeg_encoder_' a value by passing the value to the constructor in the initialization list. [useInitializationList]
[Z:/libjxl-main/tools/benchmark/benchmark_stats.cc:127] (performance) Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]

**Comment by mo271** [comment]
> [Z:/libjxl-main/lib/extras/enc/jpg.cc:169] (performance) Parameter 'exif' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue] 

I think this is actually a spurious finding, where the code analysis tools can't really handle `#if !JPEGXL_ENABLE_SJPEG`
and exif is manipulated in the "else"-case here.
>[Z:/libjxl-main/plugins/gimp/file-jxl-save.cc:604] 
(performance) Parameter 'model' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue] 

sure, and just below the same thing is true for "type", no?

>[Z:/libjxl-main/tools/benchmark/benchmark_codec_jpeg.cc:51] (performance) When an object of a class is created, the constructors of all member variables are called consecutively in the order the variables are declared, even if you don't explicitly write them to the initialization list. You could avoid assigning 'jpeg_encoder_' a value by passing the value to the constructor in the initialization list. [useInitializationList] 

this code has moved around since then, not sure if this issue still applies.

>[Z:/libjxl-main/tools/benchmark/benchmark_stats.cc:127] (performance) Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]

done


Why are you pointing out these specific code analysis findings, there must be many more. Was this causing a problem somehow or did you expect that these would cause any significant improvement in speed or whatever? 

In any case, happy to fix them and we at some point should look into fixing more clang-tidy stuff, I guess.
