### ISSUE TITLE
Lossless decompression of libjxl-testdata/jxl/splines.jxl

### ISSUE THREAD

**Issue by malaterre** [libjxl/libjxl#1811]
**Describe the bug**

AFAIK the JXL file has been losslessly compressed:

* https://github.com/libjxl/testdata/blob/main/jxl/splines.jxl

Depending on the arch libjxl is compiled I do not get the exact same decompressed buffer.

**To Reproduce**

On Debian/sid/amd64:

% djxl /usr/share/libjxl-testdata/jxl/splines.jxl /tmp/splines2.amd64.ppm && md5sum /tmp/splines2.amd64.ppm
JPEG XL decoder v0.7.0 [AVX2,SSE4,SSSE3,Unknown]
Read 59 compressed bytes.
Decoded to pixels.
320 x 320, 11.56 MP/s [11.56, 11.56], 1 reps, 8 threads.
77c4ccf6f23b320819610ebd5e1b2af0  /tmp/splines2.amd64.ppm

On Debian/sid/i386:

% djxl /usr/share/libjxl-testdata/jxl/splines.jxl /tmp/splines2.i386.ppm && md5sum /tmp/splines2.i386.ppm
JPEG XL decoder v0.7.0 [SSE4,SSSE3,Unknown]
Read 59 compressed bytes.
Decoded to pixels.
320 x 320, 8.68 MP/s [8.68, 8.68], 1 reps, 8 threads.
9ca111503859edaa6c3b1cb92ff657b7  /tmp/splines2.i386.ppm

**Expected behavior**

md5sum should match

**Screenshots**

![splines2 amd64](https://user-images.githubusercontent.com/228803/193996445-6291bc22-38ff-4b4a-989c-6f487874c3be.png)
![splines2 i386](https://user-images.githubusercontent.com/228803/193996446-d267de29-455c-4b4e-a637-eeefa3ac832a.png)

**Environment**
 - OS: Linux
 - Compiler version: gcc-12.2
 - CPU type: x86_64+x86
 - cjxl/djxl version string: JPEG XL decoder v0.7.0 [AVX2,SSE4,SSSE3,Unknown] + JPEG XL decoder v0.7.0 [SSE4,SSSE3,Unknown]

**Additional context**

**Comment by malaterre** [comment]
FYI

```
% md5sum /usr/share/libjxl-testdata/jxl/splines.jxl
222fcf2d528904bc796a7c3a3c64cd76  /usr/share/libjxl-testdata/jxl/splines.jxl
```

**Comment by jonsneyers** [comment]
I don't think exact matching of sample values across architectures should be expected for anything except modular-only bitstreams (for which we do guarantee exact reproduction up to the bit depth of the image).

Conformance thresholds are defined in terms of RMSE and peak absolute error per sample. These thresholds are nonzero to allow implementations to use SIMD in the best possible way, which can lead to very slightly different results (obviously without any visible difference).

So to understand if this is within what we would consider to be OK w.r.t. conformance tolerances or not, it would be good to check the actual amount of difference. What is the output of these commands?
```
compare -verbose -metric rmse /tmp/splines2.amd64.ppm /tmp/splines2.i386.ppm null:
compare -verbose -metric pae /tmp/splines2.amd64.ppm /tmp/splines2.i386.ppm null:
```

**Comment by malaterre** [comment]
Right, I forgot to include the output of the commands:

```
% compare -verbose -metric rmse /tmp/splines2.amd64.ppm /tmp/splines2.i386.ppm null:
/tmp/splines2.amd64.ppm PPM 320x320 320x320+0+0 8-bit sRGB 307215B 0.000u 0:00.000
/tmp/splines2.i386.ppm PPM 320x320 320x320+0+0 8-bit sRGB 307215B 0.000u 0:00.000
Image: /tmp/splines2.amd64.ppm
  Channel distortion: RMSE
    red: 0 (0)
    green: 0.803125 (1.22549e-05)
    blue: 0 (0)
    all: 0.463684 (7.07537e-06)
/tmp/splines2.amd64.ppm=> PPM 320x320 320x320+0+0 8-bit sRGB 307215B 0.010u 0:00.003
% compare -verbose -metric pae /tmp/splines2.amd64.ppm /tmp/splines2.i386.ppm null:
/tmp/splines2.amd64.ppm PPM 320x320 320x320+0+0 8-bit sRGB 307215B 0.000u 0:00.000
/tmp/splines2.i386.ppm PPM 320x320 320x320+0+0 8-bit sRGB 307215B 0.000u 0:00.000
Image: /tmp/splines2.amd64.ppm
  Channel distortion: PAE
    red: 0 (0)
    green: 257 (0.00392157)
    blue: 0 (0)
    all: 257 (0.00392157)
/tmp/splines2.amd64.ppm=> PPM 320x320 320x320+0+0 8-bit sRGB 307215B 0.020u 0:00.004
```

**Comment by malaterre** [comment]
> someone could dig out the history of file `jxl/splines.jxl`

Answering myself:

```
% jxl_from_tree /usr/share/libjxl-testdata/jxl/splines.tree /tmp/splines.jxl
% md5sum /tmp/splines.jxl
222fcf2d528904bc796a7c3a3c64cd76  /tmp/splines.jxl
```

**Comment by jonsneyers** [comment]
Splines are not currently used by the encoder at all, this is a test bitstream that was artificially produced. Splines are additional image features that are represented internally in a vector form (control points for catmull-rom splines) and painted by the decoder on top of (added numerically) the underlying pixels. The `jxlinfo` tool only inspects the image header and sees that the pixels were encoded in RGB (not XYB), so it offers the suggestion that the image is possibly lossless, but this is in any case just a possibility (there is no way for it to know the history and workflow that was used to produce the image).
In this case the pixels themselves are encoded losslessly using Modular, but they are just all black. The rest is painted with splines.

Spline rendering is defined mathematically in the spec and with infinite precision it is precisely defined; however practical implementations do things with limited precision and there can be tiny differences caused by rounding errors (which can be platform dependent and compiler dependent). The same is true for other coding tools like the DCT. For that reason we have conformance tolerances.

**Comment by malaterre** [comment]
Just FYI, I re-used some of your comments (proper git author) to add more details about jxl_from_tree:

* https://salsa.debian.org/debian-phototools-team/libjxl/-/commit/fede5c4a94c0690f39f5c93352446e7b9a2f64c6
