### ISSUE TITLE
Using cjxl with a quality value lower than 5 returns an error 

### ISSUE THREAD

**Issue by jfcalvo** [libjxl/libjxl#1968]
Using `cjxl` trying to encode a JPEG file and using low quality values returns an error:

When using `-q 5` it works as expected:

```sh
$ cjxl input.jpeg output.jxl -q 5 --lossless_jpeg=1
JPEG XL encoder v0.7.0 0.7.0 [AVX2,SSE4,SSSE3]
Read JPEG image with 42537 bytes.
Encoding [Container | JPEG, lossless transcode, effort: 7 | JPEG reconstruction data],
Compressed to 9172 bytes including container
```

But when using values lower than `5` a `Setting frame distance failed` error is showed without generating output:

```sh
$ cjxl input.jpeg output.jxl -q 4 --lossless_jpeg=1
JPEG XL encoder v0.7.0 0.7.0 [AVX2,SSE4,SSSE3]
Setting frame distance failed.
```

**Comment by alistair7** [comment]
I don't think it's valid to use `-q` with `--lossless_jpeg=1`, as any value of q less than 100 implies a lossy conversion.  Maybe instead of `-q` you wanted `-e` to control the effort/speed?  (Or if you wanted lossy, `--lossless_jpeg=0`).

In the latest development version, `-q` takes priority.  If you give any value of `-q` < 100, cjxl ignores `--lossless_jpeg` and does a lossy conversion.  So in a way this has been fixed (although IMO cjxl should at least show a warning when it gets contradictory options).

```
$ cjxl orig.jpg losslessq4.jxl -q 4 --lossless_jpeg=1
JPEG XL encoder v0.8.0 0a6bafee [AVX2,SSE4,SSSE3,Unknown]
Read 880x604 image, 148522 bytes, 346.2 MP/s
Encoding [VarDCT, d20.683, effort: 7], 
Compressed to 8675 bytes (0.131 bpp).
880 x 604, 0.05 MP/s [0.05, 0.05], 1 reps, 8 threads.
```
