### ISSUE TITLE
Ability to drop fully opaque alpha channel

### ISSUE THREAD

**Issue by Matt-Gore** [libjxl/libjxl#219]
Hello honored devs,

cjxl keeps the alpha channel even when it is fully opaque. That's not a huge deal regarding file size but it negatively affects RAM consumption and especially decoding performance.

The encoder should automatically drop such unnecessary channels and maybe have a new parameter `--always-keep-alpha` if someone really wants to do that.

Thanks!

**Comment by TheHardew** [comment]
Some programs, like minecraft with screenshots, output opaque RGBA png files and after transcoding them to jxl it is impossible to decode them to other formats directly with djxl which is also a pain. 

The image viewer I'm using doesn't support jxl so for now I've written a shell script to decode jxl to ramdisk and open it, but because of this I've got to wait after decoding for png compression.

I'm not sure how important it is to record the information that the original image was with alpha, for me it's not a huge deal but an alternative would be to add a flag to drop opaque alpha.

I'm also surprised `--premultiply` doesn't help with that, but maybe I understand wrong how it should work?

One last thing, maybe a flag to change alpha to some color would be useful for djxl, so it can save files to jpgs with e.g. black background. I might need to create a new issue for it though.

**Comment by hohMiyazawa** [comment]
Kinda curious that adding a fully opaque alpha channel to an image affects encoding time significantly.

I'm seeing a 30% increase in encoding time for VarDCT, and a 10% increase for Modular lossless, over a wide range of inputs, speed presets and quality options.

There must be some missing encoder path here.

**Comment by mo271** [comment]
Thanks for the proposal! Some changes in encoder settings were made to improve encoding time in the fully opaque alpha channel. I think it is not a good idea to drop even fully opaque alpha channels by default and even an option to do that seems out of scope for our library.
