### ISSUE TITLE
GitLab's wg1/jpeg-xl is not mirroring recent commits, out-of-date for several months

### ISSUE THREAD

**Issue by antermin** [libjxl/libjxl#2599]
Since libjxl moved to GitHub, https://gitlab.com/wg1/jpeg-xl serves as a mirror. However, today I noticed that the latest commit on main branch there is 8ae78ac6, which was authored 4 months ago.

I would like to know whether this is a technical issue, or developers have stopped mirroring commits on GitLab.

**Comment by jonsneyers** [comment]
There used to be a bot or webhook thing doing the mirroring, but for some reason it doesn't work anymore.  I think there's no real reason to keep both repos perfectly in sync, but I do think we should aim to have the most recent release also available on gitlab. Currently v0.8.2 isn't on gitlab so that should be fixed...

**Comment by jonsneyers** [comment]
Was fixed in https://github.com/libjxl/libjxl/pull/2654, please reopen if there's still a problem.
