### ISSUE TITLE
Can't disable container in cjxl via "--container=0" parameter

### ISSUE THREAD

**Issue by VcSaJen** [libjxl/libjxl#2645]
**Describe the bug**
Documentation states following:
```
--container=0|1
    0 = Do not encode using container format (strip Exif/XMP/JPEG bitstream reconstruction data).
    1 = Force using container format. Default: use only if needed.
```
Implying that this parameter is a tristate: "container when needed" (absent parameter), "force raw stream" (0), "force container" (1).
Actual behavior is: "container when needed" (0), "force container" (1).

**To Reproduce**
1) Get PNG with EXIF/XMP metadata
2) Try to convert it to jxl with `cjxl -d 0 --container=0 file.png file.jxl`
3) See that CLI writes "Encoding [Container | Modular" instead of "Encoding [Modular"

**Expected behavior**
Being able to use parameter like described in documentation

**Screenshots**
N/A

**Environment**
 - OS: Windows
 - Compiler version: ???
 - CPU type: x86_64
 - cjxl/djxl version string: `cjxl v0.9.0 c3a4f9c [AVX2,SSE4,SSSE3,SSE2]`

**Additional context**
Message from MSLP:
> looks like a bug
> you cat't force container off in presence of exif et. al. - it needs to be changed in 2 places:
> https://github.com/libjxl/libjxl/blob/main/tools/cjxl_main.cc#L989
> https://github.com/libjxl/libjxl/blob/main/lib/extras/enc/jxl.cc#L66

**Comment by jonsneyers** [comment]
https://github.com/libjxl/libjxl/pull/2697 fixes the help so it describes the actual behavior.

After https://github.com/libjxl/libjxl/pull/2686, you will be able to strip Exif metadata using `--x strip=exif` (and XMP metadata with `--x strip=xmp`).

Making `--container=0` actually drop the container in every scenario is a bit problematic, since there are various things that can make the use of a container necessary, and metadata is only one of them. Other reasons are jpeg bitstream reconstruction data and images that are not within the limits of level 5 (such as lossless >= 16-bit).
