### ISSUE TITLE
PNG tEXt chunks discarded unless XMP or EXIF

### ISSUE THREAD

**Issue by jonnyawsom3** [libjxl/libjxl#2687]
Currently cjxl will read XMP and EXIF metadata from iTXt and tEXt chunks, but they're also used to store raw text with a tag at the start which is ignored. If those tags could be turned into XMP or EXIF entries as fallback, or just a 'text' container as Jon has suggested on Discord, then the data would be retained and can be read later on.

As said in #2641, Stable Diffusion stores it's prompt settings for each image using a `Parameters` tag, and [VRCX](https://github.com/vrcx-team/VRCX/blob/master/ScreenshotHelper.cs) stores session data in screenshots using the `Description` tag.

May also be related to #1498 depending on what the original poster meant.

**Comment by jonsneyers** [comment]
Reflecting a bit more on this: currently the JPEG XL file format defines three types of metadata:

- Exif (`Exif`)
- XMP (`xml `)
- JUMBF (`jumb`)

Exif is mostly there for legacy reasons (e.g. we want it for JPEG recompression), with XMP being the more modern and generic way to add metadata to an image. JUMBF is an even more modern and generic mechanism and can be used for things like 360 or C2PA.

While the ISOBMFF container structure of JPEG XL does allow adding any other boxes (and decoders should just ignore them), so we could add something like a `text` box and put PNG tEXt chunks there, I don't think it's really a good approach to do it that way.

Instead, it would make more sense to convert those pieces of information like stable diffusion prompt settings to XMP fields and add them to that metadata — the advantage being that any application that can handle XMP will be able to show something, rather than having to rely on application-specific interpretations of free-form / non-standardized raw text boxes.

Then this becomes a question of metadata conversion (from free-form text to something more structured/standardized), which is kind of outside the scope of libjxl / cjxl. Basically you need a tool to turn a PNG with raw text chunks into one that only uses Exif/XMP/JUMBF (or convince those applications that create their own arbitrary raw text chunks to use some standardized format for their metadata).

**Comment by jonsneyers** [comment]
So I'm tempted to classify this one as `wontfix` but I'm open to other opinions.

**Comment by jonsneyers** [comment]
I'm a bit on the fence on this, see also https://github.com/libjxl/libjxl/issues/2641.

I think the current cjxl behavior of silently dropping unknown `tEXt` chunks (and other PNG chunks like `tIME` and `pHYs`) does make the most sense — in many cases, these don't actually contain any meaningful information (imo), and preserving them or even warning about stripping them is not useful.

But there might be cases where e.g. `pHYs` or `bKGD` are actually used in a meaningful way, or where raw `tEXt` chunks do contain information that needs to be preserved.

We could define a `PNGc` box ('PNG chunks') that is just a set of concatenated PNG chunks — only the ones that don't already exist in other ways in JPEG XL. So these would be allowed in there: `tEXt`/`iTXt`/`zTXt` (not containing XMP or Exif), `tRNS`, `bKGD`, `hIST`, `pHYs`, `sPLT` and `tIME`. Critical chunks (`IHDR`, `PLTE`, `IDAT`, `IEND`) would not be allowed, and also not the `cHRM`, `gAMA`, `iCCP`, `sBIT`, `sRGB` and `cICP` chunks related to colorspace (which we consider something critical in JPEG XL, but is considered 'optional' in PNG).

This box wouldn't be specifically defined in the JPEG XL spec and it also wouldn't really have to be defined there either, since the spec does just ignore boxes that aren't defined, and that's the only thing a JPEG XL decoder needs to do anyway with that box. Then again, if the information is meaningful, it would be nice if metadata-handling tools would be able to extract and display it, so it would kind of have to be part of a de-facto spec that it's done this way.

I suppose XMP can also be used represent any of this information (if needed by defining a custom XMP field for it). Converting this data to XMP seems to be the cleaner way to do things. But if the PNG already contains XMP, then this means not just writing some XMP (which shouldn't be too hard), it also means parsing the existing XMP to add new fields to it, resolving conflicts in case the info stored in the XMP disagrees with the info in the PNG chunk, etc etc. It gets a bit complicated, and I'm not sure if this is something cjxl should be doing.

Having multiple ways to do the same thing is not a great situation — e.g. physical dimensions can be stored in Exif and XMP and in the `pHYs` chunk, creation/modification timestamps can be stored in Exif and XMP and `tEXt` chunks and in the `tIME` chunk (and in the filesystem metadata for the file itself!). I think it's better to avoid such situations as much as possible, and instead recommend a single way to do things. So I think that in the end, having such a `PNGc` box is not such a good idea after all. The better approach is to centralize all the metadata in the XMP and avoid using application-specific raw `tEXt` chunks or with PNG-specific special-purpose metadata chunks (`tRNS`, `bKGD`, `hIST`, `pHYs`, `sPLT` and `tIME`).

**Comment by jonsneyers** [comment]
Closing this one in favor of https://github.com/libjxl/libjxl/issues/2641, which is basically about the same topic but it was first :)

**Comment by kmilos** [comment]
IMHO, don't thing the PNGc box is the way to go. You'll run into other formats as well that have their own freeform metadata like EXR for example. Do you plan to introduce a dedicated box for each format?

The app/format specific XMP idea makes more sense to me...
