### ISSUE TITLE
cjxl[v0.8.2] quality option not work

### ISSUE THREAD

**Issue by songjiayang** [libjxl/libjxl#2780]
**Describe the bug**

cjxl  tool can not set quality option.

**Environment**
 - OS: [linux]
 - cjxl/djxl version string: cjxl v0.8.2 [AVX2,SSE4,SSSE3,SSE2]
 # cjxl --version
cjxl v0.8.2 [AVX2,SSE4,SSSE3,SSE2] Copyright (c) the JPEG XL Project

**Additional context**

encode image failed with cmd:

```
cjxl  -e 9 -q 75 resources/jpg-8bit-gray-scale-with-icc-profile.jpg resources/a.jxl

Must not set quality below 100 nor non-zero distance in combination with --lossless_jpeg=1.
```

**Comment by mo271** [comment]
Thanks for the report!

This is intended behavior. In case you are compressing a `jpg` file, `cjxl` will by default attempt to compress it as lossless jpeg re-compression and passing a quality parameter will give the error message you are seeing.

It should encode the image with lossy compression when you pass the `--lossless_jpeg=0` flag. The default for this flag is "1", since you didn't pass a value for this flag it will be equivalent to passing `--lossless_jpeg=1`.
I think we could make a better job explaining this in `cjxl -h`, currently we don't even mention the default settings....

**Comment by mo271** [comment]
> thanks @mo271 , is `--lossless_jpeg` a hidden option, I can't find it when run `-h`

Yeah, that as well, it will show up only when running `cjxl -h -v` ( with at least one `-v`). Might it make sense to either show this option already without the `-v` or put it in the `INPUT` section like below? What do you think, @jonsneyers ?

```

JPEG XL encoder v0.8.2 [AVX2,SSE4,SSSE3,SSE2]
Usage: cjxl INPUT OUTPUT [OPTIONS...]
 INPUT
    the input can be PNG, APNG, GIF, JPEG, EXR, PPM, PFM, or PGX.
    If the input is JPEG, then by default lossless recompression will be applied.
 OUTPUT
    the compressed JXL output file
```

**Comment by songjiayang** [comment]
Copy it, thank you so much.

**Comment by DejayRezme** [comment]
This broke my ps script for reencoding jpgs. 

It seems now every user has to use this more complicated usage and add an if/then/else case into calling cjxl.

I do not see the point as to why - If I specify a distance, it's obvious I do not want lossless. If I specify distance = 0, it's obvious I want lossless. A tool should be as easy and comfortable to use as possible.

Why change the usage suddenly so that other tools or scripts using it break?

**Comment by mo271** [comment]
@DejayRezme The problem comes from the fact that for jpeg there is a difference between just storing the pixels losslessly, i.e. distance = 0 and losslessly compressing the bytes of the jpeg file, so that the original jpeg file can be reconstructed. So we need a way to specify a difference between 
```cjxl -d 0 --lossless_jpeg 1 foo.jpg foo.jxl```
and
```cjxl -d 0 --lossless_jpeg 0 foo.jpg foo.jxl```
(which is probably not what you want)
and 
```cjxl -d 1 --lossless_jpeg 1 foo.jpg foo.jxl```
 
 We tried to make the defaults such that for jpegs lossless recompression of the bytes is the default, because this way no additional artifacts will we introduced, because the operation is reversible. 
 Do you have concrete suggestions what to change about these defaults?

**Comment by DejayRezme** [comment]
Thanks for the reply @mo271

I would suggest that --lossless_jpeg is ignored if distance isn't 0. That someone needs --distance=0 and --lossless_jpeg=0 seems very rare, since the size should always certainly go up.

Or said differently, the default for --lossless_jpeg is 1 if distance=0, 
and --lossless_jpeg is 0 (or ignored) if distance > 0
