### ISSUE TITLE
JPEG XL image compression quality

### ISSUE THREAD

**Issue by yongjianbao** [libjxl/libjxl#314]
I tried to assess lossy compression quality for medical images. I used  V0.3.7. The lossy compressed images look like useless. I tried efforts 4 and 7 there is no difference. The quality I chose include 90, 98, 99. In all cases artifacts clearly visible. Are any there parameters I missed to adjust, or JPEG XL does not work for 16 bits gray scale images in lossy mode? I tried lossless, it worked fine. I can provide a comparison display of images original and compressed if there is a way to upload. The following is command line I used to compress images:

./cjxl ori_file comp_file -e 7 -q 99 --num_threads=2 --num_reps=1 -p

CJXL responded like this:

/data/out_png/ct_head_01.png
JPEG XL encoder v0.3.7 [AVX2,SSE4,Scalar]
../lib/extras/codec_png.cc:497: PNG: no color_space/icc_pathname given, assuming sRGB
Read 512x512 image, 35.8 MP/s
Encoding [VarDCT, d0.190, squirrel], 2 threads.
Compressed to 9983 bytes (0.305 bpp).
512 x 512, 3.23 MP/s [3.23, 3.23], 1 reps, 2 threads.
/data/out_png/ct_lung.png

**Comment by fabiorug** [comment]
-p lowers quality sometimes. Modular at least lossy is perfect for high qualities, vardct it needs few improvements that are arriving this month. I would wait.

**Comment by jonsneyers** [comment]
The 0.3 bpp is suspicious. Are the images perhaps 10 or 12 bit with padding in the msb instead of in the lsb? I have seen that kind of thing before, and it basically means cjxl will treat it as a very dark image and make very wrong psychovisual assumptions.

Maybe try pgm input with the bitdepth/range set correctly...

Could you share the test image?

**Comment by yongjianbao** [comment]
I love to share test images, but how can I upload? The image has a circular FOV, and padding value outside. The problem is obvious artifacts in the center of the image where is brain area with little gray value changes.

**Comment by jonsneyers** [comment]
It should be possible to attach a png here.

**Comment by yongjianbao** [comment]
The result: left: original and right: compressed:
![jpeg-xl-example](https://user-images.githubusercontent.com/29616619/125171912-67e22400-e17c-11eb-91a5-a525c63e01ae.jpeg)
Original PNG:
![ct_head_01](https://user-images.githubusercontent.com/29616619/125171945-919b4b00-e17c-11eb-8b45-67929bc354ba.png)

BTW, OpenJPH handles the same image well with qstep=0.001, effective ~0.13 bbp

**Comment by cagelight** [comment]
That "Original PNG" you've provided already has a huge amount of artifacting on it.
![mult16](https://user-images.githubusercontent.com/3761279/125172444-cbbe1a00-e187-11eb-873a-18d538b8831a.png)

**Comment by jonsneyers** [comment]
Yes as I suspected this PNG is not properly encoded in the sense that it is way too dark (as you can see in the preview here on github).

You need a PNG that looks correct in a normal viewer (e.g. a web browser). Alternatively, try the PGM input format (since PGM allows arbitrary bit depth, not only 8 or 16 like PNG).

In a 16-bit PNG, cjxl assumes white is 65535. Here it is 4095 or something like that. That means the cjxl encoder is interpreting the input image in the same way as your web browser, and it will introduce artifacts that you cannot see if you look at it like that (but if you are going to enormously brighten the image then of course you will see artifacts).

**Comment by yongjianbao** [comment]
PNG encodes data either 8 or 16 bits depth. Is there a way to tell cjxl the actual bit depth, say 12 bits?

**Comment by jonsneyers** [comment]
No, there isn't. I suggest converting to 12-bit PGM, or making a PNG that properly scales the values to 16-bit 
(do everything `v = (v*65535 + 2047)/4095`) instead of just using the darkest values.

**Comment by yongjianbao** [comment]
I managed to set bit depth in PNG to 12 bits and it works now fine. Thanks for your help.

**Comment by jonsneyers** [comment]
You're welcome! Please feel free to share your opinions on jxl's performance on medical imagery.

**Comment by jyrkialakuijala** [comment]
Often medical images are viewed with much more brightness than sRGB assumption. It may be useful to set the target intensity to around 1000 lumens for these. 

Also, often the images are stored in physical parameter space but viewed through additional windowing. There, psychovisual models such as VarDCT are questionable and would require additional work to be correct/useful. For example, in CT the value range might be [0..4095], but only values between [950..1100] are displayed from black to white -- in which case storing values [0..4095] psychovisually doesn't work, since no one is going to look at that value range.

**Comment by yongjianbao** [comment]
It is correct medical images are viewed with intensity value window. However, the window can be changed - both for different anatomic parts imaged and across different viewers. So for medical images, compression is desired to applied against the numeric data matrix - virtually ensure max fidelity of pixel values in the whole dynamic range. But if this is not possible, I think set the target intensity high makes practical sense. How can this be set?

**Comment by raysar** [comment]
`cjxl.exe in.png out.jxl --intensity_target 4000 -d 0.5`
You have an huge range of intensity target possible, 1000, 4000 and max 65504 (default is 255).
File size increase for the same distance quality, so you need do some tests with same file size.
Use --target_size (100000 for 100kB) to force encoder to find the good distance.

For all encoder parameters use cjxl.exe -h -v -v -v

**Comment by jonsneyers** [comment]
Changing the intensity target is a crude way to fix incorrectly scaled input, but it still produces an image where the brightest values are only 1/16th of the nominal white (though the nominal white is a lot brighter then).

It's better to use correctly scaled input to begin with.

The assumption of modern (perceptually optimized) lossy compression is that the image will be viewed by humans and that the color/intensity of the pixels is how it is in the image (not with big changes between the stored image and the rendered image).

For medical images, I would therefore recommend lossless compression. If lossy is really needed, then we should find a way to ensure fidelity for all possible intensity-windowed views (currently the encoder assumes there is just one view).
One option for lossy is to use lossy Modular mode in non-XYB mode (e.g. `cjxl -m -c 0 -q 90`), which is a 'stupid' (non-perceptual) form of lossy compression that treats the input numbers as just numbers without any perceptual interpretation.

**Comment by yongjianbao** [comment]
In medical imagery lossless is generally preferred. But use cases exist which call for lossy compression while basic demands remain same - the data should not be treated as "picture" based on human perception because presentation can be driven from various windows. Is it helpful that application rescale the image data to full range of certain bit depth, and then tell the coder the actual bit depth? Does this help exploit the perceptual optimization but also maintain some quantification precision across the dynamic range?

**Comment by jonsneyers** [comment]
Yes, it's certainly useful to use the full range of a certain bit depth; that way if you open the image in a regular, non-specialized viewer (e.g., a web browser) then you'll at least see something sensible (i.e., the "widest window" view) instead of seeing a dark, almost black image.

The perceptual optimization will assume some transfer curve (iirc: the sRGB one if you put it in an untagged PNG or in a PGM, linear if you put it in a PFM) and only this "widest window" view is what it is really optimizing for, i.e. it will assume that you cannot distinguish shades of bright white that are really close (while of course if you change the window to stretch [0.98, 0.99] into [0, 1] then you'll easily see things that you couldn't see before).

**Comment by yongjianbao** [comment]
Thanks for all your explanations. Just to clarify one thing: Based on what you mentioned, in JXL I can set the transfer curve to be linear (I understand this is not optimal for quantization optimization) if I need to manage quantization precision equal across the entire intensity dynamic range, right?

**Comment by jonsneyers** [comment]
In lossy modular mode, linear would be what you want to get equal quantization everywhere.

In VarDCT mode, the current encoder converts any input color space to an internal absolute color space so it knows how it looks and optimizes perceptually for it. You'd need a different encoder that doesn't do that, but we don't have that atm.

**Comment by mo271** [comment]
Please re-open if there is still an issue here.
