### ISSUE TITLE
Suggestion: accept webp as input

### ISSUE THREAD

**Issue by eclipseo** [libjxl/libjxl#315]
It would be nice to be able to convert webp directly to jxl,

**Comment by cagelight** [comment]
That would just be another dependency, it's trivial to use PNG as an intermediary. I created a script that converts lossless WebPs into lossless JXLs that way.

**Comment by sboukortt** [comment]
On the other hand, we could likely make the dependency optional, as it is for EXR/APNG/GIF input.

**Comment by jonsneyers** [comment]
I don't particularly object to this, but I don't particularly see the value of it either.

It is not the intention to turn `cjxl` / `djxl` into another ImageMagick `convert`. The rationale for now has been to add new input/output codecs only when it was needed to test encoder inputs / decoded outputs that could not be represented by the codecs that were already supported.

In the case of WebP, I don't think there's anything WebP can represent that APNG cannot already do too.

I don't mind adding more (optional) dependencies, and if someone wants to implement this, I wouldn't object, but I don't consider it a priority.

What could be useful (but a lot more work) is to attempt to represent WebP directly in jxl, that is, for lossy WebP use the same colorspace, DCT block sizes etc and try to do something close to a lossless transcoding of VP8 to VarDCT (no idea if that's actually possible though); for lossless WebP do something that mimics the internal structure of the lossless WebP (e.g. choices in predictors, context model, lz77 matches) in order to have a fast lossless transcoding that has a small but more or less guaranteed density gain.

I would encourage that kind of 'deep' WebP support, but it is a lot of work and I don't consider it a priority (compared to improving compression from pixels or from JPEG).

**Comment by hohMiyazawa** [comment]
@jonsneyers Regarding 'deep' WebP support, in the lossy VP8 case.

The 16x16 DCT is *maybe* possible if the stars align just right (one such alignment: the Walsh-Hadamard transform is not a blocker, since you can cover the "AC" from it) , but I can't see this working without having pretty much 1-to-1 equivalents for each of the ten 4x4 subblock prediction modes. Without those, you would have large errors that are quickly spreading through the image. From grepping though the jxl source code (documentation?), at least three of those prediction modes have a VarDCT equivalent.
If those other prediction modes can only be approximated, this would only be useful as a speed optimisation with substantial quality loss.

Use case? Low latency on the fly transcoding for WebP-incapable, JXL-capable, clients of WebP data? I hope I will never need that!

**Comment by landfillbaby** [comment]
libwebp is listed as an optional dependency for cjxl/djxl in the main README, but they don't compile with it, only the benchmark does...
