### ISSUE TITLE
add `JxlDecoderGetBoxSizeContents` api function

### ISSUE THREAD

**Issue by mo271** [libjxl/libjxl#3209]
We have `JxlDecoderGetBoxSizeRaw`, but it would be more useful to have an API function 
`JxlDecoderGetBoxSizeContents` that returns the size of the payload without the headers.
i.e. JxlDecoderGetBoxSizeContents = JxlDecoderGetBoxSizeRaw - 8 for non-extended boxes and 
JxlDecoderGetBoxSizeContents = JxlDecoderGetBoxSizeRaw - 8 - 8 for extended boxes.

Then probably deprecate  `JxlDecoderGetBoxSizeRaw`. 
In any case this will always talk about the compressed size in case of `brob` boxes.

**Comment by Traneptora** [comment]
The compressed size of a `brob` box is not useful if libjxl is set to silently decompress them (which iirc is the default). It makes more sense to get the uncompressed box size by default (or have a flag that lets the user choose), since the user needs to know the uncompressed size in order to malloc a buffer to store the data. The compressed size isn't particularly useful to an end-user if unless decompress-boxes set to false.

**Comment by mo271** [comment]
already done: #3212 except the deprecation of `JxlDecoderGetBoxSizeRaw` part, but perhaps it is a good idea to keep that function around as well.
