### ISSUE TITLE
Question about Exif box in the jxl file

### ISSUE THREAD

**Issue by PetrMinar** [libjxl/libjxl#3236]
Hello,

The ISO/IEC 18181-2:2021(E) standard says in 9.5 Figure 6 that the payload of the `Exif` box starts with 4 byte `tiff header offset`. The same information is also mentioned in decode.h. Should I pass the exif data to encoder in `JxlEncoderAddBox` including this `tiff header offset`? 

Thank you

**Comment by kmilos** [comment]
> Should I pass the exif data to encoder in `JxlEncoderAddBox` including this `tiff header offset`?

Yes. If your Exif data has no offset, you still need to prepend 4 null bytes.

**Comment by StefanOltmann** [comment]
The devs inexplicably opted to designate the Exif box as a "full box" in accordance with the BMFF standard, allocating one byte for the version and three bytes for flags.

This version byte holds significance in older formats based on ISO BMFF, such as the `iloc` (item location) box, which has undergone multiple version updates, leading to variations in parsing logic.

It remains uncertain whether the devs intend to treat the `Exif` box differently in the future, prompting the adoption of this approach. Currently, all values are set to zero, as mentioned by @kmilos, and no modifications have been made so far.

In contrast, the `xml ` box containing XMP data does not adhere to the full box structure. The absence of version and flag bytes in the XML box implies that its functionality cannot be altered in the future.

While this approach appears somewhat inconsistent to me, there may be valid reasons behind these decisions.

**Comment by kmilos** [comment]
> Currently, all values are set to zero

Quite often it can be 6 as a few implementations keep the `Exif\0\0` JPEG APP1 prefix.

**Comment by StefanOltmann** [comment]
Very interesting. Yeah, that’s why older and more mature metadata libraries keep a lot of compatibility stuff around to detect slightly corrupt files. Over time I will need to add more and more of that in Kim, too.

Still I’m always genuinely surprised seeing things like corrupt MPF-data straight out of Samsung phones (according to ExifTool) or wrong offsets in OOC JPEGs from the Nothing Phone.

Right now I’m thinking about how I can solve the problem [that my Fuji X-T4 adds a lot of garbage (or is it padding?) after the embedded thumbnail](https://github.com/Ashampoo/kim/issues/38). ExifTool somehow has logic to determine this as unused space. I guess they interpret the embedded thumbnail bytes.

I hope JXL will be kept more in control. Maybe readers need to be more strict this time (and deny corrupt files) to prevent a wide spread of invalid files like we see with JPEG.

**Comment by kmilos** [comment]
> Right now I’m thinking about how I can solve the problem [that my Fuji X-T4 adds a lot of garbage (or is it padding?) after the embedded thumbnail](https://github.com/Ashampoo/kim/issues/38). ExifTool somehow has logic to determine this as unused space. I guess they interpret the embedded thumbnail bytes.

I have recently patched this in Exiv2, feel free to take a look. It's again weirdly allowed by the BMFF spec.

**Comment by StefanOltmann** [comment]
You indeed have a quite impressive track record of open source contributions. 👍 🥇 

I took a look, but wasn't able to spot which pull request you refer to.

To avoid a misunderstanding: I have that problem with the Fuji JPEG, not the RAF.
But it's of course totally possible that the problem lies in the RAW file and translates to the JPEG.

**Comment by kmilos** [comment]
> I took a look, but wasn't able to spot which pull request you refer to.

This one, but it only affects BMFF files, specifically Fujifilm HEIFs: https://github.com/Exiv2/exiv2/commit/53fe85b2c4696d814cbdd4c83af66a555ba1b777

Can't remember running into any weirdness w/ their JPEGs though...

**Comment by kmilos** [comment]
@PetrMinar I had similar questions, you can check out some earlier discussions: https://github.com/libjxl/libjxl/issues/357#issuecomment-1131523216

**Comment by StefanOltmann** [comment]
@kmilos Thanks for the link. That indeed clarified where this comes from.

Until now I was thinking this box was an invention of JPEG XL.

Now I’m worried, because this definition is taken from the HEIF spec. We all know that HEIF is heavily patent encumbered. 😐

Prior to ISO BMFF support in exiv2 there was a long discussion regarding that. Personally I think it’s safe to use ISO BMFF due to its age (expired patents), but I find using box definitions from the HEIF spec really risky. JPEG XS came after HEIF, so this does not change much.

Regarding HEIC & AVIF my lib only reads what has been specified 20+ years ago to stay out of trouble. I even added a paragraph to explain why there is no support for image size & orientation: https://github.com/ashampoo/kim?tab=readme-ov-file#regarding-heic--avif-metadata

Now I read that due to my JXL support I use something of the HEIC spec, which may be covered by patents. 😞

@jonsneyers Would it not be safer to just go with the `exif` box?

**Comment by jonsneyers** [comment]
The definition of the `Exif` box is normatively specified in 18181-2: it's a 4-byte offset (usually all-zero) followed by the actual Exif payload; the offset points to where in the Exif payload the actual TIFF part of the Exif data starts. In general the Exif payload could start with something that is not the actual Exif metadata yet; the offset then helps to skip to the actual Exif information.

This definition is made that way so it coincides with what was already done in other ISOBMFF-based formats like HEIF and JPEG XS, so we don't end up with different definitions of the contents of the `Exif` box. I don't know when this definition of the `Exif` box was first used or why exactly they decided to include this TIFF offset.

Exif itself is standardized by CIPA and is outside of the scope of the JPEG XL standard.
The definition of the `Exif` box in JPEG XL is the same as in HEIF, but it is normatively specified in the JPEG XL spec and only informatively it is pointed out that it coincides with the `ExifDataBlock` as defined in HEIF. We considered it more important to follow existing practices than to save those 4 bytes and drop the offset.

Since this box definition is very simple (a 4-byte offset followed by a payload), we assume that this in itself is not a patentable 'invention', since it is something extremely trivial and non-novel. We assume that whatever patents there may be on HEIF, the definition of the `Exif` box is not one of the patent-encumbered things. Hence this should not cause trouble. And indeed, there have been no declarations made by Nokia (or anyone else, besides Google and Cloudinary who have made a Type 1 declaration, i.e. royalty-free) that state that they believe they own patents that are relevant to JPEG XL.
(while for HEIF Type 2 (non-royalty-free) declarations [were in fact made by Nokia](https://www.iso.org/cms/render/live/en/sites/isoorg/home.isoDocumentsDownload.do?t=NYoxFMZ0Wj5AWhOPIrViHH1A3HThHfQCnEoe7_v52W9Ha1G2kbF2d-uOr5FLqHQt)).

HEIF is quite complicated since it allows compositing multiple payload images (e.g. tiling or blending, or having alpha as an auxiliary image), and it is non-trivial to fully implement all of this functionality. Since we already have much of this functionality built-in in the JPEG XL codec, i.e. it supports tiling, layers and alpha already natively at the codestream level (in a better way than how it can be done at the file format level like HEIF does it), we have no real need to use HEIF and it is in fact undesirable because:

- There would be two different ways to do the same thing (e.g. RGBA in one codestream or RGB and A as two separate codestreams) which means things have to be implemented twice, at two different levels, which is an unnecessary complication and leads to redundant/duplicated code;
- All this complicated HEIF functionality may be patent-encumbered;
- Doing things at the codestream level is better for compression: e.g. we can have RGBA palettes, so for things like small icons JXL can achieve better compression than in the HEIF approach where RGB and A are independent codestreams; also we have tiling integrated into the codestream design which allows us to avoid some of the pitfalls of file format level tiling (seams at the tile boundaries, for example);

**Comment by StefanOltmann** [comment]
Thank you for your response.

> Since this box definition is very simple (a 4-byte offset followed by a payload), we assume that this in itself is not a patentable 'invention', since it is something extremely trivial and non-novel. We assume that whatever patents there may be on HEIF, the definition of the `Exif` box is not one of the patent-encumbered things. Hence this should not cause trouble.

I feel the same, but only time will tell. Let’s hope for the best. 🙂

However, I now understand much better what HEIF features you were referring to and see how JPEG XL is less complex. 👍

**Comment by PetrMinar** [comment]
Thank you all for the responses.
