### ISSUE TITLE
djxl segmentation fault with -DJPEGXL_STATIC=ON build

### ISSUE THREAD

**Issue by fredprodibi** [libjxl/libjxl#332]
I tried to build djxl with all the dependencies included because I need to run it in an other container, and it does seems to work, either it doesn't build or decompression throw a segmentation fault error. The decompression works without -DJPEGXL_STATIC=ON

this works
```
CC=clang-7 CXX=clang++-7 ./ci.sh opt
./djxl a.jxl a.ppm
```

this doesn't build
```
SKIP_TEST=1 CC=clang-7 CXX=clang++-7 ./ci.sh opt -DJPEGXL_STATIC=ON
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[43/64] Automatic MOC and UIC for target compare_codecs
ninja: build stopped: subcommand failed.
```

this build but doesn't work
```
SKIP_TEST=1 CC=clang-7 CXX=clang++-7 ./ci.sh opt -DJPEGXL_STATIC=ON -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_OPENEXR=OFF
/djxl a.jxl a.ppm
JPEG XL decoder v0.3.7 [AVX2,SSE4,Scalar]
Read 9710683 compressed bytes.
Segmentation fault
```

**Comment by deymo** [comment]
If this is inside the docker you also need to disable the viewer because we don't have qt5 static libs there: `-DJPEGXL_ENABLE_VIEWERS=OFF`

I reproed this and the reason it fails is due to pthreads in my case, this [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58909) looks related. Using `-Wl,--whole-archive -lpthread -Wl,--no-whole-archive` instead of `-pthread` in the compile line for cjxl worked, I'll send a patch to workaround this. It is not really a libjxl bug but more a representation of the general broken state of compiling static binaries.

**Comment by deymo** [comment]
from inside the `build` directory: `ninja -t commands cjxl | tail -n 1` gives you the last command needed to build `cjxl` (normally the link step). You can re-run that command and edit the command line. The fix/workaround of course would be somewhere in .cmake.
