### ISSUE TITLE
cjxl lossless -e8 and -e9 sometimes create an invalid image

### ISSUE THREAD

**Issue by tirr-c** [libjxl/libjxl#3356]
**Describe the bug**
cjxl lossless -e8 and -e9 sometimes create an invalid image according to the spec.

**To Reproduce**
Encode this image using `-d 0 -e 8`: [1225036754354229250_1](https://github.com/libjxl/libjxl/assets/2322996/6e607820-542f-443f-ae2a-5d6c4db39b5e). Pass group 10 will have a Palette transform with 557 colors with LZ77 enabled. libjxl uses `dist_multiplier = 557` to encode and decode, which doesn't match the spec (18181-1).

**Expected behavior**
LZ77 `dist_multiplier` should be 256.

**Environment**
cjxl version: `cjxl v0.10.0 6d041617 [AVX2,SSE4,SSE2]`

**Additional context**
First reported in tirr-c/jxl-oxide#268.

**Comment by TheHardew** [comment]
For images already encoded this way, are they "ruined"?

**Comment by jonsneyers** [comment]
This is why independent decoders are so nice to have. This has been a libjxl bug that went undetected because both encoder and decoder have the same bug so images still roundtripped.

We're still debating whether to treat this as a libjxl bug (which it is) and fix libjxl, or to treat it as a bug-that-becomes-spec and fix the spec. The spec way is the better way; we were losing some compression (in the specific case of images with > 256 colors per group but still few enough to do palette, i.e. less than 1024 by default) because of this bug, but then again it is annoying to invalidate existing outputs of the libjxl encoder. So it's not a clear-cut decision.

The only bitstreams affected should be modular e8+.

**Comment by tirr-c** [comment]
There are cases that it's not really possible to detect broken images; for example, if a group has only one LZ77 repeat symbol at the end of the stream, both spec and libjxl method will end up in identical bitstream and entropy-coded stream, but they will have completely different image.

**Comment by jonsneyers** [comment]
My position is to treat it as a bug-that-becomes-spec. Trying both variants in the encoder does not result in significant differences in compression. On some images, the libjxl way is slightly better, on others the current spec way is slightly better; differences are usually only a matter of a few bytes on way or the other (in the cases where there is a difference; most commonly, there is no difference at all).

**Comment by mo271** [comment]
The spec is being changed to match what the code in libjxl did in this case
