### ISSUE TITLE
Lossless density regression

### ISSUE THREAD

**Issue by TheHardew** [libjxl/libjxl#3441]
**Describe the bug**
libjxl v0.6.0 (25ef914) compresses better than v0.10.2 e1489592

**To Reproduce**
```
cjxl -e 9 -I 100 -d 0 -E 3 -g 3 --patches 1 0.6.0.jxl
JPEG XL encoder v0.6.0 25ef914 [AVX2,SSE4,SSSE3,Scalar]
Read 10240x5760 image, 189.6 MP/s
Encoding [Modular, lossless, tortoise], 8 threads.
Compressed to 8949 bytes (0.001 bpp).
10240 x 5760, 0.16 MP/s [0.16, 0.16], 1 reps, 8 threads.

cjxl -e 10 -I 100 -d 0 -E 3 -g 3 --patches 1 0.10.2.jxl
JPEG XL encoder v0.10.2 e1489592 [AVX2,SSE4,SSE2]
Encoding [Modular, lossless, effort: 10]
Compressed to 28162 bytes (0.004 bpp).
10240 x 5760,  0.315 MP/s [0.32, 0.32], , 1 reps, 16 threads.
```

**Expected behavior**
Latest libjxl should compress as well as the older version.

**Screenshots**
A zip file of both jxl files:
[images.zip](https://github.com/libjxl/libjxl/files/14764954/images.zip)

**Environment**
 - OS: Arch linux
 - Compiler version:
    17.0.6 for v0.10.2
    12.0.1 for v0.6.0
 - CPU type: x86_64, ryzen 2700x
 - cjxl/djxl version string:
     cjxl v0.6.0 25ef914 [AVX2,SSE4,SSSE3,Scalar]
     cjxl v0.10.2 e1489592 [AVX2,SSE4,SSE2]

**Comment by jonnyawsom3** [comment]
![0 6 0](https://github.com/libjxl/libjxl/assets/51539240/b1403b6b-122b-40a4-b196-8709e9af144f)
Uploading the image as a PNG for ease of viewing

**Comment by TheHardew** [comment]
Since 10k is slow to encode, here's a 1/8 nearest neighbor downscale.
```
du -b *.jxl
1846    0.6.0.jxl
2067    0.10.2.jxl
```
![src](https://github.com/libjxl/libjxl/assets/7374061/bfbdbcb5-bd16-46c1-b1a7-514a7a49815e)

**Comment by jonsneyers** [comment]
This is likely caused by my changes to the palette heuristics (https://github.com/libjxl/libjxl/pull/3420). It is expected when changing such heuristics that for some images, compression will be worse, for others it will be better. On larger sets of images, I saw an improvement on average (e.g. 0.25% improvement on the QOI test set), but such averages do hide a lot of per-image variation, e.g. one image might be 500 bytes larger and the other 600 bytes smaller.

The only way to avoid such regressions is to try both the old and the new thing whenever a change is made, making the encoder twice as slow. But such an encoder slowdown generally is not justified :)
