### ISSUE TITLE
Quantization table with index 0 not found

### ISSUE THREAD

**Issue by ilya-fedin** [libjxl/libjxl#3486]
**Describe the bug**
Getting the error mentioned in title with the following image
[image.zip](https://github.com/libjxl/libjxl/files/14985844/image.zip)

**To Reproduce**
I get the error while reading the image through Qt's QImageReader when linking it with jpegli. But I guess it should be reproducible with the utilities from libjxl repo just as well?

**Expected behavior**
Image is decoded

**Environment**
 - OS: Linux
 - Compiler version: GCC 12
 - CPU type: x86_64
 - cjxl/djxl version string: I don't have cjxl/djxl... But I used v0.10.2 tag to build jpegli.

**Comment by DCNick3** [comment]
From what I can gather, the problem is in the ordering of `SOF` and `DQT` markers.

`DQT` specifies quantization table data for one of 4 slots, while `SOF` specifies the frame header, which, among other things, specifies the slot of quantization table to be used. The `DQT` segment can be both before and after `SOF`, the only restriction is just be defined before `SOS` (the segment with actual encoded image data). Or, at least this is what `mozjpeg` does.

`jpegli` checks that the quantization table is defined when `SOF` is read, but it is not set yet. This results in "Quantization table with index 0 not found" error being printed and it bailing early.

I think moving [this](https://github.com/libjxl/libjxl/blob/67a24dd5147618f304c1017ed3221cc27ba57df0/lib/jpegli/decode_marker.cc#L107) check [here](https://github.com/libjxl/libjxl/blob/67a24dd5147618f304c1017ed3221cc27ba57df0/lib/jpegli/decode.cc#L245), and relaxing [this condition](https://github.com/libjxl/libjxl/blob/67a24dd5147618f304c1017ed3221cc27ba57df0/lib/jpegli/decode_marker.cc#L340) to actually check for `SOS` marker and not `SOF`.

**Comment by ilya-fedin** [comment]
I had a trouble understanding what kinds of jpeg it breaks as it sometimes reads and sometimes doesn't the same jpeg with your patch. Looks like I have understood now: it breaks progressive jpegs which aren't fully downloaded. So if I try to open a local progressive jpeg in application, it works just fine but if application attempts to render a not-yet-fully downloaded jpeg, it fails after applying your patch.

**Comment by ilya-fedin** [comment]
Ok, I managed dump to such a jpeg, here it is:
[image.zip](https://github.com/libjxl/libjxl/files/15001757/image.zip)

**Comment by DCNick3** [comment]
I forgot to initialize the field :sweat:. Don't know if it's the root cause, but this could have lead to the non-deterministic failures with the "Updating quant tables between scans" error message. Wasn't able to reproduce it with the image you provided.

```diff
diff --git a/lib/jpegli/decode.cc b/lib/jpegli/decode.cc
index 4a05aa9a..64690ef4 100644
--- a/lib/jpegli/decode.cc
+++ b/lib/jpegli/decode.cc
@@ -55,6 +55,7 @@ void InitializeImage(j_decompress_ptr cinfo) {
   m->found_dri_ = false;
   m->found_sof_ = false;
   m->found_eoi_ = false;
+  m->found_sos_ = false;
   m->icc_index_ = 0;
   m->icc_total_ = 0;
   m->icc_profile_.clear();
```

**Comment by ilya-fedin** [comment]
Thank you, it works now!

**Comment by szabadka** [comment]
@DCNick3 The proposed fix looks good, would you like to create a pull request with these changes? If not, I can also create it.

**Comment by DCNick3** [comment]
It's fine, you can create it
