### ISSUE TITLE
bundled highway installed globally

### ISSUE THREAD

**Issue by Hello71** [libjxl/libjxl#367]
setting aside whether bundling libraries at all is a good idea, i think libjxl should not install file "libhwy.a" globally (or libhwy_contrib.a, libhwy.pc, etc). for those who want bundled libraries, they shouldn't suddenly get unexpected highway installed alongside jxl.

**Comment by deymo** [comment]
If you pass `-DJPEGXL_FORCE_SYSTEM_HWY=ON` to cmake then it will use libhwy installed in the system and not install anything.

If you don't have libhwy installed then you won't be able to link a program that uses libjxl.a because it also needs libhwy.a; so installing one but not the other one doesn't make much sense.

Right now libhwy is not widely available so we prefer to build that one by default, but give the choice to use the one from your system.

Do you have a better proposal?

**Comment by Hello71** [comment]
yes, i see your point, it is an issue with Linux static linking. i think it would be better to rename it to libjxl-hwy.a or something like that, or better, add the objects to libjxl.a directly. i have some other comments on libjxl packaging (e.g. no way to disable installing static libraries), but don't have time to work on it now, so you can close this if not intending to work on it soon.

**Comment by Hello71** [comment]
this isn't really fixed but i don't have a better idea
