### ISSUE TITLE
libjxl-testdata/jxl/splines.tree is no longer libjxl-testdata/jxl/splines.jxl

### ISSUE THREAD

**Issue by malaterre** [libjxl/libjxl#3714]
**Describe the bug**

It seems the following is not true anymore:

```
jxl_from_tree /usr/share/libjxl-testdata/jxl/splines.tree tmp.jxl
cmp /usr/share/libjxl-testdata/jxl/splines.jxl tmp.jxl
```

Could someone please confirm that this is correct behavior as I could not see the changes documented in the 0.10.x notes.

**To Reproduce**

```
jxl_from_tree /usr/share/libjxl-testdata/jxl/splines.tree tmp.jxl
cmp /usr/share/libjxl-testdata/jxl/splines.jxl tmp.jxl
=> 1
```

**Expected behavior**

```
jxl_from_tree /usr/share/libjxl-testdata/jxl/splines.tree tmp.jxl
cmp /usr/share/libjxl-testdata/jxl/splines.jxl tmp.jxl
=> 0
```

**Screenshots**

Data is taken from libjxl-test-data

**Environment**
 - OS: Linux/amd64
 - Compiler version: gcc-13
 - CPU type: x86_64
 - cjxl/djxl version string: 0.10.3
 - jxl-test-data: ff8d743aaba05b3014f17e5475e576242fa979fc

**Comment by jonsneyers** [comment]
jxl_from_tree will use the same code as the libjxl encoder to produce bitstreams.

If there's some improvement/change in the libjxl encoder, it can happen that a different bitstream gets produced.

Looks like this has happened in this case.

I think testing that jxl_from_tree (or cjxl for that matter) produces a specific output bit-exactly is not really a good test, in the sense that there can be harmless improvements in newer versions that will produce different outputs that are equivalent.
In this case, it would be better to test that the decompressed ppm doesn't change, rather than the jxl file (also the png file could change if we would be using a different png encoder to write png output).
