### ISSUE TITLE
cjxl lossless encoding of PNG much larger than input

### ISSUE THREAD

**Issue by DamonHD** [libjxl/libjxl#426]
**Describe the bug**
cjxl v0.3.7 and v0.5.0 output significantly larger JXL than (benign) input PNG.

**To Reproduce**
(img/data.png attached, is my own creation, and released under CC0: enjoy!)
![data](https://user-images.githubusercontent.com/3265248/128751712-e2564f0b-043e-40c2-87c5-be30bc81041f.png)

% cwebp -v -lossless -m 6 -q 100 img/data.png -o img/data.png.web
% cjxl -v -s 9 -q 100 -E 3 -I 1 img/data.png img/data.png.jxl

8130 img/data.png
6820 img/data.png.webp
8642 img/data.png.jxl

(cjxl at v0.3.7, cwebp at 1.2.0)

-E 3 -I 1 at suggestion of @jonsneyers

With cjxl v0.5.0:

% cjxl -e 9 -g 3 -I 0 -P 0 --patches 0
JPEG XL encoder v0.5.0 [AVX2,SSE4]
Read 800x153 image, 32.2 MP/s
Encoding [VarDCT, d1.000, tortoise], 2 threads.
Failed to compress to VarDCT.

and:
% cjxl -v -e 9 -q 100 img/data.png
Compressed to 10485 bytes (0.685 bpp).
% cjxl -v -e 9 -q 100 -E 3 -I 1 img/data.png
Compressed to 13508 bytes (0.883 bpp).

**Expected behavior**
A JXL output file smaller than the input PNG.

**Environment**
 - OS: macOS: Darwin localhost 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
 - Compiler version: pre-built binaries from Homebrew.
 - CPU type: x86_64
 - cjxl/djxl version string: v0.3.7 and v0.5.0 [AVX2,SSE4]

**Comment by DamonHD** [comment]
Thanks for your thoughts!

Note that for my use case, above-the-fold hero images on a low-page-weight Web site, a common target *is* a 'small synthetic image', though note that the moment I am only looking at lossless.  Somewhat more than half such ATF heroes are JPEGs currently, but I will deal with them separately.

Given that compressors such as (say) DEFLATE cap the expansion that happens even on totally unsuitable input, I had simply assumed that except in very special cases that happen to suit a particular codec, I wouldn't see expansions beyond (say) a few % from a PNG under any circumstances, especially given PNG's somewhate verbose headers and thus minimum overheads!

Rgds

Damon

**Comment by DamonHD** [comment]
Here's another odd one where I'd expect JXL to do better:

```
10091 img/2021/20210221-EOallL.png
11605 img/2021/20210221-EOallL.png.jxl
 8554 img/2021/20210221-EOallL.png.webp
```

```
cjxl -v -q 100 -e 9 -E 3 -I 1 img/2021/20210221-EOallL.png 
JPEG XL encoder v0.5.0 [AVX2,SSE4]
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 1600x400 image, 37.3 MP/s
Encoding [Modular, lossless, tortoise], 2 threads.
Compressed to 11605 bytes (0.145 bpp).
```

![20210221-B1T](https://user-images.githubusercontent.com/3265248/129459725-b75e1e3a-afb0-4596-bb34-3895adda3f45.png)

**Comment by hohMiyazawa** [comment]
Is that the right image? Your CLI output says 1600x400, but the attached image is 1280x480.

**Comment by DamonHD** [comment]
Thank you!  Fiddling with too many images!  Just for reference then, that other one is:

```
3711 img/2021/20210221-B1T.png
2681 img/2021/20210221-B1T.png.jxl
2546 img/2021/20210221-B1T.png.webp
```
![20210221-B1T](https://user-images.githubusercontent.com/3265248/129460030-15fd6588-3e16-42ca-8f06-157998f88a1f.png)

**Comment by hohMiyazawa** [comment]
Finding optimal combinations of flags per is currently a manual task.
We would have to wait for better heuristics.
```
cjxl img/2021/20210221-EOallL.png-s 9 -q 100 -I 0.907 --patches=0 -g 2 -P 2
-> 8002 bytes
```

Things to try for brute forcing optimal flags:
- Group size ``-g``: all sizes form 0 to 3 are worth trying as it's never certain whether small or large groups are best for any given image.
- Predictor choice ``-P``. Usually the normal heuristics are good, but sometimes "simple" predictors like ``0``, ``1``, ``2`` and ``5`` are better.
- Patches: current patch heuristics aren't great, so often ``--patches=0``, turning them off, is better.
- ``-I`` meta adaptive trees has good defaults, but sometimes turning them off completely ``0`` or using the entire image ``1`` for learning is slightly better. For crushing, trying more values may also win you a few bytes.
- ``-E 3`` Small gains for colour images, no effect otherwise. Gives an encoding and decoding speed penalty.
- Speed: ``-s 9``, the slowest speed, is almost always best, but since the "fast" mode ``-s 3`` works somewhat differently, it may worth trying it to catch some lucky exceptions.

**Comment by DamonHD** [comment]
Fab!  May I quote you on those suggestions?

And yes, it seems that the better heuristics are important.

I note that cwebp improved significantly from V0.5.2 to V1.2.0 in robustness of compression, which I suspect was in large part heuristics improvement.

Thanks again!

**Comment by hohMiyazawa** [comment]
> May I quote you on those suggestions?

They should be roughly correct, but the source of truth would ultimately be @jonsneyers who should know these parameters by heart, and also be able to tell what heuristics can be improved.

**Comment by adamburgess** [comment]
<pre>
$ cjxl image.png whatevenisthis.jxl -q 100 --patches=0 -P 0 -e 9 -I 0.0000000000000001 -g 3
JPEG XL encoder v0.7.0 e8b073c [AVX2,SSE4,Scalar]
Read 800x153 image, 94.6 MP/s
Encoding [Modular, lossless, tortoise], 4 threads.
Compressed to <b>6889</b> bytes (0.450 bpp).
800 x 153, 0.55 MP/s [0.55, 0.55], 1 reps, 4 threads.
</pre>

**Comment by DamonHD** [comment]
Can't seem to get anywhere near that with v0.5.0: very impressive!

**Comment by Joachim-Otahal** [comment]
This issue, together with the basically same issue https://github.com/libjxl/libjxl/issues/727 are, from my point of view the most pressing ones. Reason: Imagemagick and XnViewMP, maybe others too, use it as library to compress, and inherit the compression failure(s) as bug reports. Issue 727 has the feature of having a large set of pictures on the Dilbert website to test with to detect why it actually chooses bad compression setting, even with -e 8 and -e 9.
I don't know how many people are investing their free time here, I honor your work, I am happy that jpeg-xl is actually in a well usable state and really starts spreading now.

**Comment by jonsneyers** [comment]
For these cases you have to take into account that the jxl encoder does not actually see the PNG, it only sees decoded pixels, at 24 bits per pixel. It compresses those to less than 1bpp, losslessly. It is not really fair to call this a "compression failure".

We can try to always be smaller than png, but it will be hard to do that for every possible image. At corpus level, jxl should beat png, but for any individual image, it can happen that the jxl encoder makes worse choices.

Issue #727 is interesting and investigating it could lead to encoder improvements in jxl, and it is in general interesting to find examples where png, gif or lossless webp are doing better than jxl. But it's more an opportunity to try to identify potential lossless encoder improvements, than really a bug (if you're talking about cases like a specific image being 0.7 bpp in jxl while the png is 0.5 bpp).

Closing this one since #727 is similar.
