### ISSUE TITLE
Releases page has no changelog

### ISSUE THREAD

**Issue by jo620kix** [libjxl/libjxl#43]
**Describe the bug**

On [GitLab releases page](https://gitlab.com/wg1/jpeg-xl/-/releases), there is changelog (and notes) for every release, but [GitHub releases page](https://github.com/libjxl/libjxl/releases) does not.

**To Reproduce**

Go to GitHub releases page, and click "..." to expand the details of 0.3.7. It only contains:

> Update JPEG-XL with latest changes.
> This includes all changes up to 2021-03-29 10:37:25 +0000.

**Expected behavior**

For 0.3.7:

> * Bump JPEG XL version to 0.3.7.
> * Fix a rounding issue in 8-bit decoding.
> 
> Note: This release is for evaluation purposes and may contain bugs, including security bugs, that will not be individually documented when fixed. Always prefer to use the latest release. Please provide feedback and report bugs here.

**Comment by deymo** [comment]
Releases for previous versions were made in GitLab and will stay there. We won't make new releases in GitLab. Tags are a git instrument; but "releases" are a GitHub or GitLab concept. Sure, every release in GH and GL points to a given tag in git, but the artifacts, changelog and metadata in the release are not part of git. I don't think we should create new releases for the old tags in GitHub since that'd be confusing.
