### ISSUE TITLE
Lossy / lossless indication in JXL file

### ISSUE THREAD

**Issue by eddiezato** [libjxl/libjxl#432]
**Is your feature request related to a problem? Please describe.**

A JXL file can represent several different things in terms of image compression. But there is no easy way to know how an image was encoded in JXL. Is it lossy or lossless?

**Describe the solution you'd like**

The JXL image should indicate the type of encoding process. This can be a flag in the metadata.

**Additional context**

If the user needs a bunch of lossless images for further editing, I think he would prefer to use another lossless format, such as PNG, instead of JXL, because PNG gives a clear understanding that images are compressed losslessly, which JXL lacks.

Or maybe I'm wrong, and such indicator already exists.

**Comment by xiota** [comment]
It would be useful to have the library version and encoding parameters included in the metadata.  Also a tool for showing encoding internals.

To determine lossless vs lossy, I noticed that `jxlinfo` output for lossy files have two color profile sections "original" and "data", while lossless files don't seem to make that distinction. (`jxlinfo` is in the examples folder.  I don't know why it isn't made into a bona fide tool, along with `cjxl` and `djxl`.)

**Comment by DamonHD** [comment]
Adding metadata for clients that don't need it simply detracts from the space-saving virtues of JXL.

**Comment by eddiezato** [comment]
@DamonHD
1. Lossy/lossless flag can only take: 0 [lossless], 1 [lossy], 2 [jpeg]. Not so much, I guess.

2. Do "clients" need all these values?
```
PS > .\jxlinfo 1.jxl
xsize: 1920
ysize:  1080
have_container: 1
uses_original_profile: 0
bits_per_sample: 8
exponent_bits_per_sample: 0
intensity_target: 255.000000
min_nits: 0.000000
relative_to_max_display: 0
linear_below: 0.000000
have_preview: 0
have_animation: 0
orientation: 1
num_extra_channels: 0
alpha_bits: 0
alpha_exponent_bits: 0
alpha_premultiplied: 0
original color profile:
  format: JPEG XL encoded color profile
  color_space: 0
  white_point: 1
  white_point XY: 0.312700 0.329000
  primaries: 1
  red primaries XY: 0.639999 0.330010
  green primaries XY: 0.300004 0.600003
  blue primaries XY: 0.150002 0.059997
  transfer_function: 13
  rendering_intent: 1
data color profile:
  format: JPEG XL encoded color profile
  color_space: 0
  white_point: 1
  white_point XY: 0.312700 0.329000
  primaries: 1
  red primaries XY: 0.639999 0.330010
  green primaries XY: 0.300004 0.600003
  blue primaries XY: 0.150002 0.059997
  transfer_function: 13
  rendering_intent: 1
```
If not, can you please create a github issue to remove them in terms of the space-saving virtues of JXL? 😃

**Comment by jonsneyers** [comment]
The info that jxlinfo currently gives is all in the bitstream (often implicitly, since most fields have default values), and it is information about the image that is needed anyway to decode or render the image.

Lossy or lossless however is not a property of the bitstream, but it is a property of a workflow process. Nothing stops you from making a very lossy q20 jpeg, then converting it to png, and then losslessly encoding that png to jxl, but the end result will not be lossless, since your workflow is not lossless.
Or you could start from a lossless png, then run pngquant on it to reduce it to a palette of 256 colors, and encode that losslessly with jxl. Again, not lossless. But maybe you started from an image that actually only has 5 different colors. In that case, it will actually be lossless.

If you have a q96 jpeg straight from your camera, that's in theory a 'lossy' image, but (unless you shoot in raw) it's as lossless as it gets — converting it to png actually introduces a slight loss due to DCT and color conversion rounding errors. So a jxl recompressed version of it could be considered to be a lossless image. But of course you can also first recompress it as a q50 jpeg and then losslessly recompress that to jxl.

From the bitstream point of view, there is no real distinction between a lossless and a lossy image. Sure, you can assume that when XYB is used, or VarDCT mode, or modular delta palette, then the image is probably lossy. At least at the moment that is the case. But suppose in the future there are cameras that produce jxl files, then likely they will produce something that uses XYB and VarDCT mode, and it will be (as) lossless (as it gets).

My point is: keeping track of the workflow is not the responsibility of the codec itself — at least, it hasn't been in the past: in jpeg or png you have no way of knowing what workflow lead to that image, and if that was a lossy or lossless workflow.

You could define some metadata for it (e.g. add an Exif or XMP field for it), but there still will be no guarantee that the metadata corresponds in any way to the reality, or that it is even present.

There is no such thing as a "lossless format". There are format that _can do_ lossless, but that doesn't mean that what you get is actually lossless. A lot of png images come from jpeg sources. There are several tools that do lossy processing to make png files smaller. There is no bitstream distinction between a really-lossless png and an actually-lossy png. The same is true for jxl: it _can do_ lossless, but you can also do all kinds of lossy things (possibly before the encoder even sees the image).

You can make assumptions and forensically try to estimate whether an image is lossy or lossless (just like you can try to detect if a png is an ex-jpeg, or assume that if a png is photographic and it uses a palette, that it's probably lossy), but doing those forensics is outside the scope of a codec library.

From a pragmatic point of view: if you assume good-faith actors, you can just use a workflow convention like naming your files `image-lossless.jxl` and `image-lossy_q80.jxl`, if you just want to keep track of what is what.

**Comment by jonsneyers** [comment]
That said, it wouldn't be hard to define an optional container-level metadata box that basically contains the encoder version string and the encode options that were used. It would be something you would typically strip (since it's just extra bytes that don't contribute much), but it might be useful in some workflows. There's probably much more though than just the jxl part of the workflow that you may want to keep track of (like the origins of the source material, the processing that was done on them, etc).

**Comment by eddiezato** [comment]
It's not about the birth of the image or its life path. It's about some pixels that have to be stored without loss and without me having to remember that or making notes in filenames. 😁

As a user, I don't care how an image in webp format indicates that. What matters to me is that the image has this indication.

**Comment by jonsneyers** [comment]
WebP images don't have such an indication, afaik. Maybe a tool can tell you that the lossless webp codec was used, but it cannot tell you if it was used in a lossless way (and not e.g. with a lossy "near lossless" encode option).

**Comment by xiota** [comment]
With JPG, if the same quant tables are used, there's very little loss with recompression.  Does something similar with JXL?  If so, it would be useful to know the settings that were previously used.

**Comment by eddiezato** [comment]
For images created with `cwebp`, you can see the lossless/lossy flag with `webpinfo`. Yeah, it also reports lossless for near-lossless, but for general use such indication is sufficient.

**Comment by VcSaJen** [comment]
Wait, is that true? I thought you already can clearly see if it's lossy or lossless in file itself, I guess not?..
@xiota agree. Many tools are just black boxes with no options: if you save, you save, that's it. If the output is PNG, you don't have to worry, exactly zero of them mess with image data itself, it just saves as-is. If output is JPEG, you already know that it's lossy, so that's that. If output is JXL, you have no choice but to do image diff between JXL and PNG and at this point you better off just saving as PNG and converting it to JXL yourself.

**Comment by jonsneyers** [comment]
Many tools do mess with the image data if you save as PNG. Photoshop does use PNG8 if you check the "Smaller file" option, for example.

We could show the colorspace of the first frame, if it's XYB then it's lossy, if it's RGB then it's likely lossless, if it's YCbCr then it's likely a recompressed JPEG. But just know that there is no way to guarantee that an image is actually lossless, since like I said, that's not a property of the pixel data, but of the workflow process.

**Comment by VcSaJen** [comment]
@jonsneyers 
> if it's RGB then it's likely lossless
Can current version of reference implementation create lossy RGB via available API, or it's just theoretical?

**Comment by jonsneyers** [comment]
> @jonsneyers
> 
> > if it's RGB then it's likely lossless
> 
> Can current version of reference implementation create lossy RGB via available API, or it's just theoretical valid file that can be created in the future via custom implementation? If it's just theoretical, it's good enough for me.

It's not just theoretical: e.g. if you use `cjxl --lossy-palette` or `cjxl -m -c 1 -Q 50`, you can get lossy jxl files that use RGB.

Default encode settings will however use XYB for lossy and RGB for lossless, at least for now.

**Comment by VcSaJen** [comment]
@jonsneyers gotcha. For now I'll just assume that all *.jxl files in the wild are in a lossy format, unless personally converted by myself.

**Comment by jonsneyers** [comment]
Yes, same as with *.png, basically.

**Comment by VcSaJen** [comment]
In internal files of mobile software and videogames? Sure. In art sites? Photography banks? Nope, never. Anyway, this is getting offtopic.

**Comment by xiota** [comment]
For 24mp images from my digital camera... Lossless from PNG (after RAW processing) is over 90MB.  Lossy with d=0.01 is 40MP.  Lossy with d=0.1 is 13MB (camera JPG is around 12MB).  Lossy with d=1 is 2.3MB.

**Comment by VcSaJen** [comment]
Interesting, that would be helpful. Do you have results for anime/cartoon images? Though I assume the size varies more, depending on complexity of images.

**Comment by jonsneyers** [comment]
> > Yes, same as with *.png, basically.
> 
> In internal files of mobile software and videogames? Sure, and 8-bit palette speaks by itself anyway. In art sites? Photography banks? Nope. Anyway, this is getting offtopic.

Offtopic indeed, but how many photographic png files out in the wild do you estimate are ex-jpegs? I have no clue, but I wouldn't be surprised if it was over 50%, considering the amount of cameras that produce jpegs. Importing a jpeg in photoshop, adjusting the colors a bit and saving the result as png doesn't make it lossless. I suspect that kind of workflow is quite common though.

In pixel art, png8 palette images can be lossless.

My point is: it is an illusion that there is such a thing as 'lossless formats' or that you can unambiguously detect from bitstream headers that something is or is not lossless. Forensically, you can make a very educated guess, but it remains a guess. That's true for png, and it is also true for jxl.

If you really want to keep track of workflows in a robust way, there are approaches being developed that will allow that, e.g. see https://contentauthenticity.org/. It requires cryptographic checking of provenance and attribution chains. These kind of approaches are currently being designed (a.o. within JPEG, in the Adhoc Group on Fake Media), and there will likely be new kinds of metadata standards for them. It will be possible to store such metadata in jxl, through the JUMBF mechanism.
But even then, you can just strip that metadata and end up with "anonymous" pixels and there will be no way to know for sure if they are lossless or not.

**Comment by xiota** [comment]
I'm losslessly transcoded a lot of old photographs.  I don't have a lot of cartoon images.  I did have a few old drawings that I losslessly transcoded from PNG.  Size was pretty variable depending on the source.  Having info about the compression methods and settings would be useful.  It could even save info about the source format if the lossyness of the workflow is in question.

**Comment by xiota** [comment]
> But even then, you can just strip that metadata and end up with "anonymous" pixels and there will be no way to know for sure if they are lossless or not.

The a building could burn down and lose all the records.  Doesn't mean there wasn't value in producing the records in the first place.

**Comment by jonsneyers** [comment]
Yes, that makes sense. But it _is_ metadata, not an inherent property of the codestream.

In libjxl, we make a sharp distinction between image data and metadata. Things like ICC profiles and Exif orientation we consider to be image data, and they are part of the codestream. Anything that impacts how an image is to be rendered (including of course the pixels themselves) is part of the codestream. Anything else we consider to be metadata, and it is handled as a complete black box. The file format can store Exif/XMP/JUMBF, but for libjxl that's just a blob of bytes without any meaning (for Exif we specify that the orientation from the jxl codestream counts and the one in the Exif blob is to be ignored).

Now we could define metadata that stores a cjxl/libjxl version number and encode params, or any other information, and we could instrument `cjxl` to (optionally) add such metadata, and `jxlinfo` to display it. Probably the easiest way to do that is to define a new box type for it, `jxlm` or something (for jxl metadata or jxl makernote), that just contains arbitrary ascii text that `cjxl` writes there and `jxlinfo` prints out. Another option is to use some Exif or XMP field for it, or define a new field for it, but then it gets trickier to write/read it (and you cannot just change the Exif/XMP of a losslessly recompressed JPEG, reconstruction will fail if the size doesn't match what is expected).

Feel free to make a pull request in that direction, I can see how that could be useful in some use cases.

**Comment by xiota** [comment]
There's precedent in video and audio codecs with storing version and settings metadata in files.  Using a `jxlm` box or some such seems like a good approach as long as it doesn't break existing jxl files.  If I ever learn enough about the container structure, I'll look at approaching it.

**Comment by eddiezato** [comment]
There are two images:
```
Name  Length
----  ------
1.jxl 394277
2.jxl 392810
```

Let's try to encode each to png and then to lossless jxl:
```Powershell
ls *.jxl | % {
    djxl $_ temp.png
    cjxl -m temp.png "$($_.Basename)x.jxl"
    ri temp.png
}
```

Guess which was lossy and which was lossless:
```
Name    Length
----    ------
1.jxl   394277
1x.jxl  394277
2.jxl   392810
2x.jxl 8606267
```

So there is some difference between lossless and lossy jxl. At least for me it would be useful to know this without having to do decoding/encoding.

**Comment by ValZapod** [comment]
So there is no way to see it, like in JPEG 2000, where one transform is lossless 5/3 and the other (9/7) is lossy... Well, in the end is not H.264 like that too? In particular we know that H.264 Main10 profile is never lossless, and the only lossless profile is high 444 predictive. Ha. That means that while for 8 bit -qp 0 does give lossless for 10 bit -qp 0 if high10 is selected is not lossless.

That is why in ffmpeg jpeg xl has not lossless / lossy like -c:v jpeg2000.

**Comment by gitoss** [comment]
> WebP images don't have such an indication, afaik. Maybe a tool can tell you that the lossless webp codec was used, but it cannot tell you if it was used in a lossless way (and not e.g. with a lossy "near lossless" encode option).

It's correct that cwebp doesn't store information if "near lossless" pre-processing took place - but that's a similar case like losslessly compressing a lossy jpeg.

However concerning metadata at least a binary 0/1 lossy/lossless indication would be welcome because it enables you to see if an image is definitely NOT lossless, i.e. not best for archival or best for editing/re-compression.

**Comment by eddiezato** [comment]
I think this issue can be closed, since the indication I was asking about in the first place already exists in some way.
```
> cjxl 0.jpg tran.jxl -j 1
JPEG XL encoder v0.10.2 e148959 [AVX2]
Encoding [JPEG, lossless transcode, effort: 7]
Compressed to 437.8 kB including container

> cjxl 0.jpg mod.jxl -j 0
JPEG XL encoder v0.10.2 e148959 [AVX2]
Encoding [Modular, lossless, effort: 7]
Compressed to 1865.7 kB (6.673 bpp).
1920 x 1165,  0.839 MP/s [0.84, 0.84], , 1 reps, 16 threads.

> cjxl 0.jpg var.jxl -j 0 -d 1
JPEG XL encoder v0.10.2 e148959 [AVX2]
Encoding [VarDCT, d1.000, effort: 7]
Compressed to 312.6 kB (1.118 bpp).
1920 x 1165,  11.410 MP/s [11.41, 11.41], , 1 reps, 16 threads.

> ls *.jxl | ft Name, @{ Label = 'jxlinfo'; Expression = { (jxlinfo $_ *>&1 | ? {$_.StartsWith('JPEG XL image') }).Split(',')[-2].Trim() }}

Name     jxlinfo
----     -------
mod.jxl  (possibly) lossless
tran.jxl (possibly) lossless
var.jxl  lossy
```

**Comment by MasterInQuestion** [comment]
If encoding does not introduce quality loss: the procedure is lossless.

    Note AD/DA (Analog <=> Digital) conversion is regardless lossy.
    And a core component of imaging sensors is denoise.

    True lossless wouldn't matter for most cases.
    What truly matters is unacceptable quality loss.
\
\
    Note losslessly re-encoded lossy data do not necessarily bloat:
    Those do bloat just stored in manner unfriendly for reuse.
    (proper denoise may workaround)
