### ISSUE TITLE
Unable to encode using JXL_TYPE_UINT32

### ISSUE THREAD

**Issue by xiota** [libjxl/libjxl#462]
**Describe the bug**

Encoding fails when I try to use `JXL_TYPE_UINT32` <s>or `JXL_TYPE_FLOAT16`.</s>
* <s>With JXL_TYPE_FLOAT16, JxlEncoderSetBasicInfo fails.</s>
* With JXL_TYPE_UINT32, JxlEncoderAddImageFrame fails.

**To Reproduce**

* Edit lines 163-172 of `examples/encode_oneshot.cc` to use `JXL_TYPE_UINT32`/<s>FLOAT16</s>
* Assign corresponding values to `bits_per_sample` and `exponent_bits_per_sample`.
* Compile and run using output from `decode_oneshot`.

**Expected behavior**
Encoding should succeed if those types are supported.  Other types succeed (eg, JXL_TYPE_UINT16), although the jxl is junk because the image data and assigned data types don't match.  Am I missing a setting somewhere?

**Environment**
 - OS: Ubuntu 21.04, Linux 5.11.??
 - Compiler version: gcc 10.3.0
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.6.0 2ebc6ec

**Additional Contxt**

I just found sections in[ `encode.h`](https://github.com/libjxl/libjxl/blob/7d6a7bd229db977bf94e1c1698cf07bf254ae2cc/lib/include/jxl/encode.h#L170-L173) and [`encode.cc`](https://github.com/libjxl/libjxl/blob/7d6a7bd229db977bf94e1c1698cf07bf254ae2cc/lib/jxl/encode.cc#L159-L165) indicating that `JXL_TYPE_{UINT32,FLOAT16}` are not yet supported by `JxlEncoderAddImageFrame` and `JxlEncoderSetBasicInfo`.  So the behavior described in this issue are expected, for now.

#483 Partially addresses this issue.

**Comment by xiota** [comment]
I just found comments in[ `encode.h`](https://github.com/libjxl/libjxl/blob/7d6a7bd229db977bf94e1c1698cf07bf254ae2cc/lib/include/jxl/encode.h#L170-L173) and [`encode.cc`](https://github.com/libjxl/libjxl/blob/7d6a7bd229db977bf94e1c1698cf07bf254ae2cc/lib/jxl/encode.cc#L159-L165) indicating that `JXL_TYPE_{UINT32,FLOAT16}` are not yet supported by `JxlEncoderAddImageFrame` and `JxlEncoderSetBasicInfo`.  So the behavior described in this issue are expected, for now.

**Comment by jonsneyers** [comment]
uint32 is not supported by the JPEG XL spec, the maximum bit depth for integer samples supported by the spec is 31.

The maximum bit depth for integer samples supported by the current internals of libjxl is 24 (since we are internally using float, which has 24 mantissa bits so it can only losslessly represent integers up to 24-bit).

We could still at some point allow UINT32 to pass buffers, as it might be useful for >16-bit integer case. But it's not something that is allowed in the JxlBasicInfo; if bits_per_sample is 32, then it cannot be an integer sample type, in fact exponent_bits_per_sample has to be exactly 8 in that case (i.e. the number of mantissa bits is at most 24, or 23 if you don't count the implicit mantissa bit).

It is a misconception that the JxlBasicInfo data type has to match the pixel_format; with https://github.com/libjxl/libjxl/pull/873 I hope that this will be better documented.

Closing this issue for now; proposals on how to further improve the documentation are of course still welcome, preferably as a pull request 😉.
