### ISSUE TITLE
Licensing Complications for the GDK Pixbuf Loader

### ISSUE THREAD

**Issue by thebombzen** [libjxl/libjxl#512]
The GDK Pixbuf Loader located at `plugins/gdk-pixbuf/pixbufloader-jxl.c` looks *remarkably* similar to the one in the FLIF repository, which I wrote. You can find it here: https://github.com/FLIF-hub/FLIF/blob/master/src/flif-pixbuf-loader.c

I do not mind this being used in the reference software, but there are some potential caveats that need to be considered.
- First, my code is not written from scratch. It, itself, is a derivative of the WebP version, which can be found here. https://github.com/aruiz/webp-pixbuf-loader
- That code, and also my derivative, is licensed under the GNU Lesser General Public License, version 2 or later.
- I signed a CLA which preserves the license and copyright of my work, but grants permission for you to use it. https://github.com/FLIF-hub/FLIF-CLAs/blob/master/signed/thebombzen-cla.txt

The GDK Pixbuf loader itself is a dynamic library loaded by `dlopen(3)` so licensing only this component under LGPLv2 or later should not break any existing code, but I'm not certain because I Am Not A Lawyer. I would also be happy to re-license the code to match the JXL project license, or even transfer or relinquish copyright, but IANAL and I am not sure if the previous authors' permission would need to be requested to do that.

This is what open source is about - sharing code, and I'm pretty happy to see this here, but I'm just not sure how the licensing works with regard to this. Thoughts?

**Comment by jonsneyers** [comment]
IANAL either, but AFAIU the two easiest options are:

- get permission from all authors to relicense to BSD
- rewrite the plugin so it no longer is based on LGPLv2-licensed code

Making the plugin LGPLv2 while the rest of the code is BSD seems risky to me — I don't know if that can be done without causing all of libjxl to become LGPLv2. Maybe it is possible, but I think we better consult a lawyer first then. We don't want to give libjxl a copyleft license because that would prevent it from being integrated into proprietary software, or even in projects like Firefox that have a license that is not compatible with LGPLv2 as far as I understand.

**Comment by thebombzen** [comment]
If permission is granted that's the simplest option. There's only three authors on the file, since I derived it from a snapshot in 2017, which had only three authors. It was cut at [978af60e](https://github.com/aruiz/webp-pixbuf-loader/commit/978af60e72f553a83a73e797d62c634279e3e28e). Those three authors are:
- @aruiz: Alberto Ruiz <aruiz@gnome.org>
- @DavidMazary: David Mazary <dmazary@gmail.com>
- (no public github) Přemysl Janouch <p.janouch@gmail.com>
Alberto Ruiz is the original author and owner of the repository.

For what it's worth, this is why I don't like the GPL (or LGPL) since it (by design) is fairly restrictive and eats up other licenses. It seems counterproductive the software license restricts how you can integrate code to the point of being unnecessarily cumbersome even in open source projects.

**Comment by DavidMazary** [comment]
I'm happy to relicense my commits as needed.

**Comment by veluca93** [comment]
We're working on rewriting the plugin - the old one had a few issues anyway (no color management, no streaming decoding, no animation/saving support) and overall I believe it's simpler to rewrite it.

**Comment by aruiz** [comment]
A GDK pixbuf loader being LGPL poses no problem whatsoever in this case, the LGPL is explicitely designed to act as a liberal license towards any work it links to and its copyleft aspect only comes into play for derived work of the library licensed as LGPL.

I hate to be that guy, but if this is the only concern towards LGPL licensing I am not too keen on grating an exception from my original copyright.

Are there other concerns other than "making the plugin LGPLv2 while the rest of the code is BSD seems risky to me"?

**Comment by jonsneyers** [comment]
> A GDK pixbuf loader being LGPL poses no problem whatsoever in this case, the LGPL is explicitly designed to act as a liberal license towards any work it links to and its copyleft aspect only comes into play for derived work of the library licensed as LGPL.
> In other words, it is only viral within the boundaries of the plugin itself. There are plenty of proprietary apps that link to LGPL libraries such as GTK or GStreamer.
> 
> I hate to be that guy, but if this is the only concern towards LGPL licensing I am not too keen on grating an exception from my original copyright.
> 
> Are there other concerns other than "making the plugin LGPLv2 while the rest of the code is BSD seems risky to me"?

The point is moot since the plugin needed to be rewritten anyway, but are you sure that it works that way?

I agree that LGPL libraries can be used by (any license) applications (if they use dynamic linking), but that's not what this is about.

We have a BSD library here (libjxl) that we want to keep having a permissive license to allow distribution (including static linking) in any software (FOSS with any license, proprietary software).

If the gdk-pixbuf plugin is done as a purely external project, then I see no issue licensing it as LGPL: it's then clearly an LGPL thing that depends on a BSD thing (libjxl) and another LGPL thing (libgtk), and that's fine.

If however we have it here, then I think we need to be more careful, because it could become a matter of legal argument what the direction of dependency is: does the gdk-pixbuf plugin depend on libjxl, or does libjxl depend on the plugin? I think the answer is quite clear in this case, but perhaps some lawyers or judges might think otherwise — e.g., we think about dependencies/linking as a directional thing, but it might be possible to convince a judge that linking is not a directional thing ('connecting' A to B or B to A is the same thing). Having the two things in the same repo, distributed together, could be used as evidence that they are 'linked' to one another. Now **IF** (big if) libjxl would depend on something LGPL-licensed, then basically libjxl becomes LGPL-licensed, which is something we want to avoid. Now I know this is a relatively absurd reasoning (libjxl obviously does not depend on plugins that use it, it's the other way around), but still, lawyers have made more absurd claims than that, and I think we should aim to minimize the likelihood of FUD tactics being used against libjxl.

Anyway, the point is moot in this case, and also IANAL so take my interpretation of things with a couple of grains of salt.

**Comment by aruiz** [comment]
Since the copyleft aspect of the LGPL only kicks in at binary distribution time and only the people shipping the binary are liable, more likely than not it'll be the distros and not yourself. You should not worry.

If you are rewriting the pixbuf loader from scratch you don't need my re-licensing, sure, but I wanted it to make it clear that LGPLv2 as a choice for the loader should be of no legal concern for your use case, even if you include the pixbuf loader in the same repo.

**Comment by jonsneyers** [comment]
I'm not worrying about legal liability, I am worried about adoption. Some legal departments will just grep the repo for the string "GPL" and flag the whole thing as "sorry, you can't use this" if they encounter the license anywhere. Yes, that's stupid. Stupidity exists though, and it can be an obstacle to adoption.

**Comment by DamonHD** [comment]
LGPL really isn't GPL, but in anycase someone may want to use the whole libjxl work in a way that would become impossible or impractical or expensive legally with even one element of it being any flavour of GPL or LGPL because of the restrictions inherent even in LGPL.

But, I Am Not A Lawyer, even if I could point you to some good lawyers in this area that I am using right now.

Rgds

Damon

**Comment by aruiz** [comment]
> I'm not worrying about legal liability, I am worried about adoption. Some legal departments will just grep the repo for the string "GPL" and flag the whole thing as "sorry, you can't use this" if they encounter the license anywhere. Yes, that's stupid. Stupidity exists though, and it can be an obstacle to adoption.

At that point why would they adopt gdk-pixbuf at all?
