### ISSUE TITLE
Overall feedback for app integration

### ISSUE THREAD

**Issue by rsebbe** [libjxl/libjxl#513]
Hi,

we want to support JXL in our photo app (iOS). It is a full featured format that brings unusual yet useful capabilities like float encoding, especially for HDR, but not only. We've built it and internally integrated it (v0.5), and we have this feedback so far. (If this is not the right place for this feedback, please let me know)

- Memory footprint
Memory usage seems pretty steep when encoding a 12MP photo with JXL. I measured spikes > 800MB in Xcode when doing so, which cause crash on older iOS device lacking some memory. Is it expected? Will that stay that way in later release? Are there options that let you control that aspect?

- Encoding duration
It looks like it takes over 10s to encode a 12MP on iPhone 6S, about 5s on iPhone XS (compiled with optimisations). Also, is that expected?

- Data input API
Currently, we have to provide data as float RGB triplets, or RGBA quadruplets. It would be interesting to get an RGBX option (ignored alpha) if that makes sense in the input API, as rendering format very often is aligned on 4 floats per pixel. Currently it is required to re-layout data (consumes CPU / mem) prior to pass it to `libjxl`

- Line-based encoder API for large images
In some situations, we generate very large picture that typically can't be stored in memory (too large). We generate them band by band, and we encode each band as they are made through `libjpeg` line-feeding. This approach does not seem possible at this time with `libjxl`. Is that something that will possible at some point in the future, or is it inherently impossible to achieve that because of the method used?

- Metadata passing
We'd be very interested to pass along all the EXIF / TIFF / etc. metadata to the generated image file. Currently, this does not seems possible. Even orientation seems to be ignored.

- Color space support
Could you consider adding linear ROMM / ProPhoto color space to the built-in API ? This color space makes a lot of sense for photo editing workflows.

Thank you.

**Comment by veluca93** [comment]
> Hi,
> 
> we want to support JXL in our photo app (iOS). It is a full featured format that brings unusual yet useful capabilities like float encoding, especially for HDR, but not only. We've built it and internally integrated it (v0.5), and we have this feedback so far. (If this is not the right place for this feedback, please let me know)

Hi! Thank you for the feedback, and for integrating JPEG XL! This is indeed the (a?) right place for it :)

I will answer to some of your questions, and let others deal with the rest.

> 
> * Memory footprint
>   Memory usage seems pretty steep when encoding a 12MP photo with JXL. I measured spikes > 800MB in Xcode when doing so, which cause crash on older iOS device lacking some memory. Is it expected? Will that stay that way in later release? Are there options that let you control that aspect?
> * Encoding duration
>   It looks like it takes over 10s to encode a 12MP on iPhone 6S, about 5s on iPhone XS (compiled with optimisations). Also, is that expected?

For both of those, I suspect that there is a common cause - patch/dot detection. It should be possible to significantly reduce memory and time usage by reducing the encode effort to 6 instead of 7 - the effect should be minimal on most photographic content.


> * Line-based encoder API for large images
>   In some situations, we generate very large picture that typically can't be stored in memory (too large). We generate them band by band, and we encode each band as they are made through `libjpeg` line-feeding. This approach does not seem possible at this time with `libjxl`. Is that something that will possible at some point in the future, or is it inherently impossible to achieve that because of the method used?
This should in theory be possible, although the format features might require buffering *some* of that data (likely a few 8x8 downsampled fields, and the output image). I don't think this will be a problem in practice, but I'd like to hear from you about that.

> Thank you.

Thank you again!

**Comment by jonsneyers** [comment]
Regarding orientation: that can be set by setting the corresponding field in the JxlBasicInfo (https://github.com/libjxl/libjxl/blob/main/lib/include/jxl/codestream_header.h#L185). Like color space, we don't consider orientation to be 'merely' metadata, since it impacts image rendering.

Regarding metadata: There currently is no encode/decode api yet to add/retrieve 'real' metadata (Exif/XMP/JUMBF), I recently proposed something but we're still discussing how exactly to do it: see https://github.com/libjxl/libjxl/pull/501.
'Real' metadata is handled at the container (file format, 18181-2)  level, not at the codestream level (18181-1).

ProPhoto should be possible by using `JXL_PRIMARIES_CUSTOM` and `JXL_WHITE_POINT_CUSTOM` and setting the primaries and white point to the right values (they're listed e.g. here: https://en.wikipedia.org/wiki/ProPhoto_RGB_color_space), and using `JXL_TRANSFER_FUNCTION_LINEAR`.

Adding a convenience function for ProPhoto could in principle be done, but the same could be said about other 'popular' colorspaces like Display P3, Adobe RGB (1998), Rec.2100 PQ, etc. If we do that, I'd rather do it by defining some JxlColorEncoding constants that can be used with `JxlEncoderSetColorEncoding()` than to add a function like `JxlColorEncodingSetToSRGB()` for each of them.

Adding an RGBX pixel format option shouldn't be too hard I think. Any objections against adding that, @lvandeve / @deymo ?

**Comment by rsebbe** [comment]
> For both of those, I suspect that there is a common cause - patch/dot detection. It should be possible to significantly reduce memory and time usage by reducing the encode effort to 6 instead of 7 - the effect should be minimal on most photographic content.


Great, I'll do some testing in that direction, and let you know how it goes.
 
> This should in theory be possible, although the format features might require buffering _some_ of that data (likely a few 8x8 downsampled fields, and the output image). I don't think this will be a problem in practice, but I'd like to hear from you about that.
> 

OK. The way we typically generate the full size image band by band. Band height can be something like 256px or 512px, and typically cover the full width. We're talking of photos over 10k x 10k, which could be hard/impossible to represent in their entirety in RAM. Would be an extremely useful feature, as this is exactly why we had to use libjpeg instead of iOS's Image IO (which requires full-size image in RAM). That also would allow lower spec'd hardware to implement encoding, as a 12MP RGBA already takes ~200MB just by itself. Definitely opens the door to more outcomes.

**Comment by rsebbe** [comment]
> Regarding orientation: that can be set by setting the corresponding field in the JxlBasicInfo (https://github.com/libjxl/libjxl/blob/main/lib/include/jxl/codestream_header.h#L185). Like color space, we don't consider orientation to be 'merely' metadata, since it impacts image rendering.
> 

Yes, I did that (EXIF orientation 6 while encoding), but jxlinfo reports 1 on that image. Note that I used v0.5 for encoding, and v0.3.7 for jxlinfo.

> Regarding metadata: There currently is no encode/decode api yet to add/retrieve 'real' metadata (Exif/XMP/JUMBF), I recently proposed something but we're still discussing how exactly to do it: see #501.
> 'Real' metadata is handled at the container (file format, 18181-2) level, not at the codestream level (18181-1).
> 

Great. Looking forward to that. We'll then need to convert the CGImage (Image IO) ones to your API to get going.

> ProPhoto should be possible by using `JXL_PRIMARIES_CUSTOM` and `JXL_WHITE_POINT_CUSTOM` and setting the primaries and white point to the right values (they're listed e.g. here: https://en.wikipedia.org/wiki/ProPhoto_RGB_color_space), and using `JXL_TRANSFER_FUNCTION_LINEAR`.
> 

Definitely. I'll give it a try. For now, I'm using the (linear - no tone curve) sRGB with extended gamut (beyond 0-1), which in theory enables unlimited color representation as well [btw, is extended gamut fully supported?]. Because it's easier to setup that way in libjxl API.

> Adding a convenience function for ProPhoto could in principle be done, but the same could be said about other 'popular' colorspaces like Display P3, Adobe RGB (1998), Rec.2100 PQ, etc. If we do that, I'd rather do it by defining some JxlColorEncoding constants that can be used with `JxlEncoderSetColorEncoding()` than to add a function like `JxlColorEncodingSetToSRGB()` for each of them.
> 

Could be nice for easier specification. Possibly not required though as there is a workaround.

**Comment by jonsneyers** [comment]
It could be that v0.3.7 of jxlinfo didn't properly report orientation, I remember fixing a bug in it. Could you check what the current jxlinfo reports? Also: does the image display OK? (i.e. when you decode, do you get the oriented pixels if you don't explicitly say you don't want the decoder to orient it for you?)

Extended gamut linear sRGB should be fully supported, yes (of course with the caveat that if you ask for the pixels in an integer format like uint16, they will be clamped to the sRGB gamut - but as long as you use floats, it's fine). It's the intermediate representation cjxl uses too.

**Comment by rsebbe** [comment]
> > For both of those, I suspect that there is a common cause - patch/dot detection. It should be possible to significantly reduce memory and time usage by reducing the encode effort to 6 instead of 7 - the effect should be minimal on most photographic content.
> 
> Great, I'll do some testing in that direction, and let you know how it goes.


Here's some results with 7 v. 6 effort (rough approximations from the gauges, did not run through profiler):

**iPhone XS**
Effort 7 - 12MP - duration=4s - RAM delta=700MB
Effort 6 - 12MP - duration=2.4s - RAM delta=300MB

**iPhone 6s**
Effort 7 - 12MP - duration=10.5s - RAM delta=700MB
Effort 6 - 12MP - duration=5.1s - RAM delta=300MB

Effort 6 should solve my crashing issue on older devices (available RAM exceeded). About file size, effort 6 is slightly larger (~5%), but I guess this depends on contents.

**Comment by veluca93** [comment]
> Effort 6 should solve my crashing issue on older devices (available RAM exceeded). About file size, effort 6 is slightly larger (~5%), but I guess this depends on contents.

That's a larger difference than I expected - I guess you could benefit from being able to just disable dots and patches, but IIRC that's not possible with the current API...

Anyway, good to know that the performance is better - I hope this is enough for practical usage!

**Comment by rsebbe** [comment]
> It could be that v0.3.7 of jxlinfo didn't properly report orientation, I remember fixing a bug in it. Could you check what the current jxlinfo reports? Also: does the image display OK? (i.e. when you decode, do you get the oriented pixels if you don't explicitly say you don't want the decoder to orient it for you?)

Unless I made a mistake with input structure, I'm encoding (v0.5) with orientation 6, and jxlinfo (v0.5) still reports orientation 1 on generated data.

<img width="400" alt="Screenshot 2021-08-31 at 17 35 58" src="https://user-images.githubusercontent.com/369828/131533260-a5fb56ff-66cb-4be7-893b-67655abf528b.png">


> Extended gamut linear sRGB should be fully supported, yes (of course with the caveat that if you ask for the pixels in an integer format like uint16, they will be clamped to the sRGB gamut - but as long as you use floats, it's fine). It's the intermediate representation cjxl uses too.

Great, thank you. I'll do some additional testing at a later time to confirm there is no loss of information between sRGB extended range & linear ROMM / ProPhoto.

**Comment by jonsneyers** [comment]
#535 and #630 should help to fix some of the issues reported here.

Thanks again for the feedback!

If you have further feedback, feel free to open more issues. Preferably different ones per issue, that makes it easier to track what is resolved and what is still open.

Closing this one now since I think everything here has been addressed; please reopen if I missed something.

**Comment by ductranit** [comment]
Hi @rsebbe, I wonder can you please share how do you setup on ios? 
I'd like the build the JXL decoder on ios app as well but I'm having a trouble with this library setup.
Thank you!
