### ISSUE TITLE
Conformance Corpus Confusion

### ISSUE THREAD

**Issue by veluca93** [libjxl/libjxl#584]
Some image from the conformance corpus have issues when decoded with the API:

https://github.com/libjxl/conformance/tree/master/testcases/grayscale_jpeg has incorrect colors

https://github.com/libjxl/conformance/tree/master/testcases/opsin_inverse  fails to decode

**Comment by lvandeve** [comment]
The opsin_inverse case should be fixed with https://github.com/libjxl/libjxl/pull/593

For the grayscale_jpeg issue, Luca notes multiple issues: it decodes correctly to JPEG, it decodes to a black image with djxl, it decodes to a green-colored image with the api

**Comment by lvandeve** [comment]
About the grayscale JPEG image:

The image in the conformance test set testcases/grayscale_jpeg/input.jxl is encoded with the kGray color space, and has a gray ICC profile. The encoded frame is encoded with VarDCT, and has its color transform set to "kNone", not to "kYCbCr". Given that it's a grayscale JPEG, I think both "none" and "ycbcr" could be argued for.

However, the specification doesn't specify how to use grayscale kNone in VarDCT mode. When encoding and decoding, and doing so with a single color channel in VarDCT, you need to choose in which of the 3 VarDCT channels you encode it: in the first, second, third, or all three? In XYB color transform it's in fact in the second and third because XYB (0,1,1) is gray. In the case of YCbCr, it's the second because YCbCr is specified to be encoded with Y in the second VarDCT channel. For the case of kNone, the encoded VarDCT channels are assumed to match the color encoding or ICC profile, so typically they are RGB. For grayscale ICC profile / color encoding, the best choice would be to make R=G=B equal, similar to what it does in the case of modular. So the conformance test image should not only set the second channel, but all three.

The API output is a green JPEG because it read the channels as R=0, G=has content, B=0. Not sure yet why the djxl output is black.

In conclusion, to fix this bug there are multiple things to do:

-check if the specification tells directly or indirectly in any way which channel(s) should be used in VarDCT for grayscale kNone image, with probably R=G=B as solution that it indirectly implies. Amend if necessary

-fix JXL encoder: when writing a grayscale JPEG image with kNone, write to all three VarDCT channels, not only the second one

-possibly let JXL encoder choose kYCbCr for grayscale JPEG image, for that case storing the image with the data only in the second VarDCT channel makes sense

-possibly fix decoder: it should not have output a correctly reconstructed JPEG on this incorrectly encoded conformance test image, it was interpreting the channels as kYCbCr while in fact it should have interpreted them as kNone. The JPEG reconstruction should take the color transform into account

**Comment by jonsneyers** [comment]
Not sure if the spec is clear about it, but what would make sense to me for grayscale kNone images is to encode them like it is done in Modular mode: only "the first" channel gets the values (in Modular the two other channels just don't exist in this case, which is not an option in VarDCT). Which one is the "first" channel is kind of confusing though. Internally, we store things in XYB in case of kXYB, RGB in case of kNone, and CbYCr in case of kYCbCr. The second channel (the one that has luma, basically) is often coded first though (but not always). In Modular mode, XYB gets encoded as YX(B-Y), but the two others get encoded as they are (RGB or CbYCr), and the case of grayscale kNone is encoded as just a single channel.

Since VarDCT always encodes 3 channels, I would suggest to always use XYB or YCbCr in case of grayscale, so it's clear that Y has the grayscale values. For kNone grayscale VarDCT, we _could_ use chroma from luma and let R=G=B for free when only encoding G, or we could define G to be the only channel that matters in that case. Probably it's a good idea to do the former in the encoder (or just avoid kNone grayscale completely) and do the latter in the decoder.

**Comment by jonsneyers** [comment]
Is this one OK now, or is there something that needs to be resolved still?

**Comment by veluca93** [comment]
I think it should be OK but @lvandeve knows more
