### ISSUE TITLE
Using JxlDecoderSetPreferredColorProfile with JxlDecoderRewind

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#632]
Hello,

I use `JxlDecoderSetPreferredColorProfile` in my programs.

I observed that after `JxlDecoderRewind`, the preferred color profile is forgotten, and the image data decoded later corresponds to the image's default color profile (like the JxlDecoderSetPreferredColorProfile call was never used).

I have to subscribe for the `JXL_DEC_COLOR_ENCODING` event again, because that's the only place where JxlDecoderSetPreferredColorProfile could be set again now.

Is it desired behavior?
If it is desired, please add info to documentation.
Or could be the JxlDecoderRewind call be made to remember the color profile preference?

**Comment by jonsneyers** [comment]
I agree that either we properly document the current behavior (basically rewind conceptually forgets everything and is the same thing as reset, except you have to use it with the same input and it might do some things more efficiently this time because it cached some useful info), or change the current behavior to remember things like this that (and then properly document that).

I don't have a strong opinion on what is the best thing to do; keeping the current behavior is less work and maybe conceptually a bit cleaner (since it will be arbitrary where to draw the line between what it remembers and what it forgets, e.g. you could also remember image buffers etc). But it needs to be documented better in any case.

**Comment by mo271** [comment]
Let's change the behavior instead of just documenting what is going on right now.

**Comment by mo271** [comment]
> change the current behavior to remember things like this that (and then properly document that).
> 
What exactly are "things like this"?

**Comment by mo271** [comment]
@jonsneyers I'm not entirely sure how to implement this best. 
Currently don't reset this:
```
  dec->thread_pool.reset();
  dec->keep_orientation = false;
  dec->render_spotcolors = true;
  dec->coalescing = true;
  dec->desired_intensity_target = 0;
  dec->orig_events_wanted = 0;
  dec->frame_references.clear();
  dec->frame_saved_as.clear();
  dec->frame_external_to_internal.clear();
  dec->frame_required.clear();
  dec->decompress_boxes = false;
  ```
  which corresponds to calls to 
  ```
JxlDecoderSetCoalescing
JxlDecoderSetDesiredIntensityTarget
JxlDecoderSetDecompressBoxes
JxlDecoderSetKeepOrientation
JxlDecoderSetRenderSpotcolors
JxlDecoderSkipFrames
JxlDecoderSubscribeEvents
 ```
  
  This works now, and could just be documented. If we want `JxlDecoderSetDesiredIntensityTarget` to keep state across resetting the decoder, I guess we would need to keep `dec->passes_state` and  `dec->got_all_headers`, but doing this naively doesn't work, because it breaks the frame skipping (see pending pull request). Making `output_encoding_info` part of the `JxlDecoderStruct` is also not straightforward, because there are places where only the `PassesDecoderState` is passed. 
  
Any thoughts?

**Comment by jonsneyers** [comment]
As long as it is clear what gets reset to defaults and what doesn't, it's OK with me. It does need to be documented properly though.

**Comment by mo271** [comment]
Ok, going with documenting the status quo then.
