### ISSUE TITLE
GIMP plug-in use too much memory during image loading

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#638]
Hello @xiota ,

I was able to open this animation http://188.121.162.14/jxl/animation.jxl via GIMP 2.10 plug-in:
![gimp-jxl_frames](https://user-images.githubusercontent.com/52529860/134706397-92476d44-0457-4732-961c-1f39aef0f01f.png)

However it look lot of time and consumed lot of memory.

Animation has 330 full-hd frames. The plug-in first load all the frames into memory with FLOAT precision and at the end, it shrinks all the data 4-times by converting to U8 precision. Temporarily >10GB of memory is used.

Isn't it better to load the frames in 8bit depth directly? Or if you load data in JXL_TYPE_FLOAT format, it can be converted to 8bit after each frame, so less memory is occupied during loading.

**Comment by xiota** [comment]
@novomesk Thank you for letting me know.  I'm using float because JXL uses float internally, and using float on the GIMP side seemed to resolve some ICC profile profile issues.  #642 converts the layers to the destination precision before they're inserted into the image, as you suggest.

**Comment by novomesk** [comment]
@xiota I tried the new code in your `gp-memory-use` branch.

The big animation now loads significantly faster.

There is one different thing I am not sure about.

The plug-in from gp-memory-use branch (built under MSYS2) loads a [JXL file](https://github.com/libjxl/conformance/blob/master/testcases/progressive/input.jxl) this way:
![gimp210](https://user-images.githubusercontent.com/52529860/134886070-a65f510b-c1ef-4e89-b53d-8b011a702fc8.png)

but in GIMP 2.99 on Linux using my plug-in the picture is brighter:
![gimp299](https://user-images.githubusercontent.com/52529860/134886282-9cba0557-6f6e-474f-a053-c3bf906837ca.png)

**Comment by veluca93** [comment]
Looking at the images, it looks like the gp-memory-use branch has some kind of colorspace handling issue... I can confirm the brighter image is correct.

**Comment by xiota** [comment]
@novomesk Thanks for letting me know.  I'll take a look at it.  I've been having difficulties with the ICC profiles.  When one set of images loads correctly, another doesn't, and vice versa.

**Comment by xiota** [comment]
@veluca93 The version of the plugin in main has the same issue as the gp-memory-use branch.  Getting ICC profiles to load correctly has been an ongoing issue, especially when the ICC profile and the internal encoding don't agree.  For instance, the red car image has an ICC profile with an Rec.709 curve (based on the file name), but the JXL internal encoding is linear.

**Comment by novomesk** [comment]
Isn't the problem here?
```
          if (JXL_DEC_SUCCESS != JxlDecoderGetColorAsICCProfile(
                                     dec.get(), &format, _PROFILE_ORIGIN_,
                                     icc_profile.data(), icc_profile.size())) 
```
You are getting original ICC but the returned pixels are in `JXL_COLOR_PROFILE_TARGET_DATA`

**Comment by xiota** [comment]
@novomesk I don't think so.  When I disable all the convoluted ICC profile handling in the plugin, the result is the same.  That is also how to extract the original ICC profile.  For example, if an image uses the prophoto color space.  What does your plugin do with this: [prophoto-icc.zip](https://github.com/libjxl/libjxl/files/7239371/prophoto-icc.zip)

Can GIMP 2.99 and 2.10 be installed side-by-side so I can try your plugin?

**Comment by novomesk** [comment]
I never tried to have GIMP 2.10 and 2.99 at the same time.

I suggest to compare rendering with latest unstable Google Chrome, they have generally good color management.

Using my Qt plug-in brings different visual results in different applications. Many Qt viewers don't have color management yet. DigiKam is good, newest gwenview have limited color management.

Try also **eog** which used gdk-pixbuf loader.

In the past I tried this viewer:
https://github.com/libjxl/libjxl/tree/main/tools/viewer

**Comment by xiota** [comment]
@novomesk  The problem is the gamma curve.  The image I asked about earlier doesn't render properly in Chrome.  (Left is how Chrome renders the JXL.  Right is how it renders the PNG.)

![chrome-jxl-rendering](https://user-images.githubusercontent.com/8353098/135012438-e3b287b4-ff82-4f37-b721-3c462dee8efb.jpg)

**Comment by novomesk** [comment]
Try to rebuild libjxl, there was obviously some bug there.

For example I used JPG from your prophoto.zip, converted using cjxl to .JXL and then back to .JPG via djxl.

The final .JPG was much brighter than original.

**Comment by xiota** [comment]
cjxl/djxl don't use the API.  What they do is independent of the plugin.

The jpg is there for reference so you'd know how the jxl is supposed to look.

The jxl and png were both converted to prophoto with icc profile attached.  They *should* look the same when properly loaded.

**Comment by jonsneyers** [comment]
How did you encode that jxl file? It looks like it is encoded incorrectly (maybe it was given linear sRGB input but the encoder was told the data was in ProPhoto, or something like that?). When I convert the png or jpg with cjxl, I get a jxl that looks fine (in any viewer that does proper color management).

**Comment by xiota** [comment]
@jonsneyers  cjxl/djxl look like they're doing color management that the API doesn't.  If I convert to sRGB in GIMP, out of gamut colors get lost.  So I've just been sending the data to the API as-is.

**Comment by jonsneyers** [comment]
For encoding with the API, either you do lossless encoding with uses_original_profile, or lossy but then you have to give the input in a colorspace the encoder API understands (since it indeed doesn't have arbitrary icc color management). If there's a way to convert to linear sRGB floats without clamping to 0..1 in GIMP, that would be a good option (but of course if it clamps, then you lose out of gamut colors). Another option could be to always convert to a very wide gamut space like ProPhoto and give the input that way (but then you need to manually make a JxlColorEncoding with custom primaries).

For decoding with the API, the easiest option is to use the TARGET colorspace, but in non-lossless cases that will always be (unclamped) linear sRGB, and if GIMP cannot take that as input without clamping first, then that's a problem that will in general be hard to resolve without adding a dependency to a color management library. I _think_ GIMP should be able to understand unclamped linear sRGB though. See also:
https://www.gimpusers.com/forums/gimp-developer/16416-three-questions-about-opening-an-image-and-converting-it-to-linear-light-rgb

**Comment by xiota** [comment]
@jonsneyers I'll rework the ICC handling.  I think GIMP does clamping when converting colorspaces, at least at the image level.  Or maybe there is a different API call I need to use.  The forum posts seem to be about how GIMP handles things internally.

**Comment by ctrlcctrlv** [comment]
As luck would have it, libjxl#1870 now fixes this too.
