### ISSUE TITLE
Unable to decode older JXL file using C API again

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#725]
Hello,
I downloaded genessa8.jxl from the old issue:
https://gitlab.com/wg1/jpeg-xl/-/issues/228
and I am unable to decode it using C API again. This problem was fixed in the past but it is happening again.
djxl can convert it but with warning:
`Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...`

jxlinfo gives following messages:
```
jxlinfo genessa8.jxl
box: type: "JXL " size: 12
box: type: "ftyp" size: 20
box: type: "jbrd" size: 2894
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/jpeg/jpeg_data.cc:106: JXL_FAILURE: Unknown app marker type 7
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/fields.cc:618: JXL_RETURN_IF_ERROR code=1: visitor.Visit(fields)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/jpeg/dec_jpeg_data.cc:23: JXL_RETURN_IF_ERROR code=1: Bundle::Read(&br, jpeg_data)
Decoder error
Couldn't print basic info
```

**Comment by jonsneyers** [comment]
It looks like this jxl file has corrupt `jbrd` data. It was likely encoded by an encoder from before the `jbrd` data spec was finalized.

The jxl codestream data itself is fine, so the image can still be decoded, but it's not possible to reconstruct the original jpeg bitstream.

In the C API we'll have to decide if we want to treat such input as corrupt (because the `jbrd` is invalid) or as a valid image until you try to reconstruct the jpeg bitstream. @lvandeve any opinion on this?

**Comment by mo271** [comment]
I think there's not much we can do about this right now. Newly created files should work flawlessly. 
Thanks for the input in any case!
