### ISSUE TITLE
Several static Libs/Binaries contain full path of (many) CC files for errors/asserts/warnings

### ISSUE THREAD

**Issue by gorza47** [libjxl/libjxl#730]
Hi,

In the release mode the static Libs/binaries should not contain the filenames (for sure not the full path) of the CC files used in several error messages/warning/asserts.

I found the "__FILE__" usage in:

(version 0.6)

hwy\base.h
decode.cc
encode.cc
base\status.h

This is nice in Debug mode, but not in the Release mode ... or add a flag to CMake.

**Comment by deymo** [comment]
@gorza47 I don't understand why full paths are not ok in release mode, but relative paths and the debug messages (from the asserts that use `__FILE__`) are ok. If the issue is including unnecessary strings in the release binary bloating the file size, then use `-DJXL_DEBUG_ON_ABORT=0` in the cflags to get rid of the strings (both messages and file paths). It is not always the case that "release mode" means size-optimized, it depends on the use case so we give you the option.

We could set -fmacro-prefix-map when compiling with gcc in cmake too. For some reason when I build locally from a build directory I don't see absolute paths, I see "../lib/jxl....", but anyway using fmacro-prefix-map when supported sounds reasonable to me.
