### ISSUE TITLE
Full commit history

### ISSUE THREAD

**Issue by EwoutH** [libjxl/libjxl#8]
Thanks for starting the move to full open source!

However, to understand the codebase better, it would be hugely beneficial to have the full git commit history available, and not the squashed ones from the current public GitLab repo.

**Comment by jonsneyers** [comment]
I'm personally OK with that for my commits, but you have to understand that when these commits were made, they were made in the knowledge that it was a private, not a public repository they were made in.

Also, while it would perhaps be interesting for historians, I don't know if publishing the full and detailed history of the codec development is something all contributors would feel comfortable with. Often bigger commits were a team effort, but in the end they always end up getting committed by a specific person; that might lead to incorrect perceptions of what people actually contributed to the project. So I can see reasons for considering the past history as something that was "done collectively by the whole team" instead of revealing all individual commits.

In any case, I think the important thing is to do development "in the open" from now on, and also to enable others to start contributing. There is still quite a bit of stuff to be done :)

**Comment by EwoutH** [comment]
Would anonymizing them be a solution? That way all the information useful to contributors about how and why certain parts of the codebase were created is available, but the privacy of contributors stays protected for development that happend when it was a private repo.

**Comment by veluca93** [comment]
@deymo probably has more information here.

I don't particularly see publishing the full history of the repo as a priority; I think author names are not the only thing we might not want to be public, and I personally don't particularly enjoy the prospect of looking at all commits to check if it would be OK to publish ...

I also don't think that the commit history would help people that much in understanding why JPEG XL is the way it is, but that might just be my opinion :P

**Comment by deymo** [comment]
The code evolved quite a bit from research code building a new image format in PIK and FUIF, and with the input from the JPEG XL process to what's today. I don't think that having the full history of that would help understanding the codebase so I don't see it as a priority right now, and it will be less and less important as the time goes by.

The main blocker I see is that the agreement with all contributors at the time all those commits were made is that they were not public; so making them public now is a breach of that agreement. I don't think anonymizing changes this (list of main contributors is in CONTRIBUTORS.md anyway). Some contributors still around might be ok with the change but probably not all of them and it would also take time for us to revisit the history to make sure that there are no issues of any kind with publishing it, or some parts of it, or a redacted version of it. There were good reasons at the time why the JPEG XL reference codec development was not in the public and we were eager to move the development to the public and open it up to external contributors in a sustainable way. So moving forward we will continue here.

I hope you understand the situation. I will close this issue since I don't think we can do much about this.

**Comment by EwoutH** [comment]
Thanks for the extensive reply!
