### ISSUE TITLE
cjxl crashes with some black and white images

### ISSUE THREAD

**Issue by k2arim99** [libjxl/libjxl#822]
as it says in the title, i was doing bulk transcode of manga jpg's and it failed on some while working on others from the same batch of files, which is pretty strange given the fact that i assume in manga pages are processed in bulk with the same settings
heres the logs
```
cjxl -v Aria_v01_007.jpg try.jxl
JPEG XL encoder v0.7.0 a3571ec4 [SSE4,Scalar]
Read 853x1200 image, 124.1 MP/s
Encoding [Container | JPEG, lossless transcode, squirrel | JPEG reconstruction data], 2 threads.
Compressed to 173811 bytes (1.358 bpp).
853 x 1200, 13.48 MP/s [13.48, 13.48], 1 reps, 2 threads.
Average butteraugli iters:       0.00
Total layer bits headers   	  0.008350%       116
Total layer bits TOC       	  0.025984%       361
Total layer bits quantizer 	  0.001799%        25
Total layer bits quant tables	  0.008422%       117
Total layer bits order     	  0.016411%       228   [c/i:  1.00 | hst:       1 | ex:       6 | h+c+e:      29.126]
Total layer bits DC        	  5.269136%     73204
Total layer bits ControlFields	  0.003599%        50
Total layer bits AC        	  0.925000%     12851   [c/i: 78.00 | hst:    1590 | ex:       0 | h+c+e:  142078.595]
Total layer bits ACTokens  	 93.573661%   1300017
Total layer bits modularGlobal	  0.109624%      1523   [c/i: 11.00 | hst:     190 | ex:       0 | h+c+e:    6416.376]
Total layer bits modularTree	  0.058015%       806   [c/i:  2.00 | hst:      30 | ex:      21 | h+c+e:      97.069]
Total image size              1389298   [c/i: 92.00 | hst:    1813 | ex:   24783 | h+c+e:  173376.666]
```

vs one that worked

```
Average butteraugli iters:       0.00
Total layer bits headers   	  0.007296%       102
Total layer bits TOC       	  0.025823%       361
Total layer bits quantizer 	  0.001788%        25
Total layer bits quant tables	  0.008369%       117
Total layer bits order     	  0.014020%       196   [c/i:  1.00 | hst:       1 | ex:       4 | h+c+e:      25.397]
Total layer bits DC        	  5.437647%     76017
Total layer bits ControlFields	  0.021889%       306
Total layer bits AC        	  0.993293%     13886   [c/i: 75.00 | hst:    1706 | ex:       0 | h+c+e:  142758.850]
Total layer bits ACTokens  	 93.329285%   1304721
Total layer bits modularGlobal	  0.099787%      1395   [c/i:  9.00 | hst:     174 | ex:       0 | h+c+e:    6925.644]
Total layer bits modularTree	  0.060802%       850   [c/i:  2.00 | hst:      32 | ex:      21 | h+c+e:     101.497]
Total image size              1397976   [c/i: 87.00 | hst:    1915 | ex:   24603 | h+c+e:  174388.513]
Including container: 175378 bytes (1.367 bpp).
Allocations: 477 (max bytes in use: 3.204004E+07) 
```

(sorry if the logs are a bit too big)
i can provide the samples just tell me how

**Comment by jonsneyers** [comment]
Please provide a sample. It might be something new, or it might be similar to an already known issue (like #803)

**Comment by k2arim99** [comment]
sure thing
this one transcodes cleanly
https://anonfiles.com/p0Y6C4T9u1/Aria_v01_006_jpg
this one doesnt 
https://anonfiles.com/h4Y3CaT8uc/Aria_v01_007_jpg

**Comment by jonsneyers** [comment]
I managed to download the test case, but could you please just attach it next time :) that's a quite spammy host...

It looks like the problem case is a grayscale JPEG that includes (unused) quantization tables for the chroma channels. https://github.com/libjxl/libjxl/pull/359 doesn't help here because those unused quantization tables are different from the luma quantization table. Since the `jbrd` jpeg bitstream reconstruction data does not store quantization tables, but they are stored in the jxl codestream itself, and there is no way in jxl to store quantization tables that are not actually used, this is a case of a JPEG that cannot be losslessly represented in jxl. Not much can be done about that.

If and when https://github.com/libjxl/libjxl/pull/358 lands, it will cause cjxl to no longer just silently fail but to instead transcode the jpeg image data losslessly without creating a `jbrd` box that allows you to reconstruct the jpeg file. The image would be preserved losslessly in this case, but it would just not be possible to produce the exact same jpeg file again (since the original jpeg file was somewhat malformed, containing quant tables for components that don't exist).

One thing you can do however, is to clean up the jpeg file before giving it to cjxl, e.g. by doing `jpegtran -copy all Aria_v01_007.jpeg > Aria_v01_007-clean.jpg`. The result of that will transcode nicely.

There is nothing we can do at this point to make that original jpeg file reconstructible, but maybe it would make sense to have an encode option to do the equivalent of the jpegtran thing: strip the redundant quant table, and still add a `jbrd` so you can get back a jpeg that is almost the same as the original, just without the redundant quant tables and possibly other 'problematic' things that cannot be represented. Though it might be better to instead have an option to create a "minimal" `jbrd` that is enough to reconstruct a functionally equivalent jpeg (same APP markers, same image data) but not (necessarily) identical to the original (possibly lose relatively irrelevant information like padding bits, huffman tables, restart markers etc).

**Comment by hohMiyazawa** [comment]
What would the size difference be between a "minimal" functionally equivalent ``jbrd`` and a bitexact ``jbrd``? I'm guessing it's not much, but the relaxed "functionally equivalent" level of required losslessness is common.

**Comment by k2arim99** [comment]
wups sorry ,i was just worried that github would do weird stuff to the images im new :) also, i forgot to mention that i got them to work by stripping them with imagemagick, which is what you explained. 
glad to help

**Comment by jonsneyers** [comment]
> What would the size difference be between a "minimal" functionally equivalent `jbrd` and a bitexact `jbrd`? I'm guessing it's not much, but the relaxed "functionally equivalent" level of required losslessness is common.

In the typical case, both would be quite small. There are cases though of `jbrd` failing to be written because the amount of tail data is too large (e.g. https://github.com/libjxl/libjxl/issues/803), or where it doesn't fail but has a few MB of tail data stored in the `jbrd`. Stripping that out loses information (since there might be a whole other file in the tail data after the end of the jpeg bitstream), but it might be desirable in case you don't care about that data but you still want to be able to convert the image data itself back to JPEG losslessly.

**Comment by mo271** [comment]
Considering #358 has landed and that the images can't be downloaded anymore, I'm closing this. Feel free to reopen if we can still handle those somewhat malformed jpg files better.
