### ISSUE TITLE
Jpeg recompression efficiency

### ISSUE THREAD

**Issue by futurevessel** [libjxl/libjxl#934]
I've been comparing Jpeg-XL recompression of existing jpeg files with PackJPG (https://github.com/packjpg/packJPG) and the latter is giving me ~8% better compression based on a pretty large (2gb) chunk of sample jpegs consisting of primarily photos (nature, faces etc), but also animation and 3d renders.

I was wondering if there's any way to lower this gap in compression efficiency, at first I though that PackJPG might be omitting some data but checksums of the decompressed jpegs showed that they were indeed exactly as the originals.

I tried some more aggressive options, but the best I came across '-I 2 -e 9 -E 3' gave me less than 1% improvement

**Comment by jonsneyers** [comment]
One thing we're currently not doing yet, is compressing exif/xmp metadata that might exist in the jpeg and that can get large in some cases.

Other than that, it is to be expected that pure archival recompression methods like PackJPG and Lepton can reach somewhat better compression. They don't have to be decodable to pixels directly, nor progressively. So they can do things like using the AC in the context model of the DC, which is good for density but anti-progressive. They also don't have to care about parallel decoding. I guesstimate that jxl is paying about 1-2% compression density to avoid being inherently sequential and to allow parallel decode. Maybe another 1% is lost due to being progressively decodable (if you use AC in DC prediction/context, you can make DC cheaper). And maybe another 2% is lost by not being able to hardcode DCT8x8 and have a context model specifically designed for that, but having to use a generic VarDCT context model, where you cannot assume that the blocks around you are also all 8x8 blocks.

**Comment by futurevessel** [comment]
I see, well that makes perfect sense. I suppose there are no plans of adding a more aggressive compression mode specifically for archival purposes, that isn't bound by these limitations ?

Anyway, thanks for the quick answer and for a great image codec, truly the first one I've seen that is realistically (and even likely) a replacement for both jpeg and png as the 'de facto' standards for lossy and lossless.

**Comment by jonsneyers** [comment]
There might be a bit of margin for encoder improvements within jxl itself: for the AC context model we currently use a relatively simple heuristic; there are likely better choices.

Theoretically you could make a variant of jxl that always does everything in a single group (instead of doing things in 256x256 groups) - that's just changing a constant in the code from 256 to "inf" (65536 will do in case of jpeg recompression). It wouldn't be spec compliant of course, but that would improve compression a little.

We don't have plans to add "archival only" modes that would be slow(er) to decode and not compatible with the current spec, for a small gain in compression. The main design goal was to be able to represent existing JPEGs losslessly (to allow a transition that doesn't involve lossy transcoding), not really to get the best possible compression for that. For new images, encoding with native jxl will in any case be better than any kind of recompressed jpeg.

**Comment by futurevessel** [comment]
Again, makes sense, it provides an easy upgrade path for existing jpeg files, while adding a nice compression bonus without sacrificing performance. Speaking of which, is there a way to forego the ability to recreate the original jpeg when doing a lossless conversion, and thereby saving space ?

**Comment by jonsneyers** [comment]
Yes, you'd strip the `jbrd` box in the container. Currently there's no `cjxl` option to do only that (`--strip` will strip `jbrd`, but also exif/xmp), but I suppose you could do it with a generic ISOBMF tool.

**Comment by futurevessel** [comment]
Ah, thanks!
