### ISSUE TITLE
conformance regression with conformance/testcases/animation_spline_5/input.jxl ? 

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#984]
**Describe the bug**

with git of today, compilation of examples/jxlinfo. Output:

```
$ ./jxlinfo.exe ~/gitroot_64/conformance/testcases/animation_spline_5/input.jxl
./lib/jxl/decode.cc:2100: invalid signature
Decoder error
Couldn't print basic info
```

**Expected behavior**

basic info of this file

**Environment**
 - OS: Win10
 - Compiler version: gcc
 - CPU type: x86_64
 Highway scalar

**Comment by jonsneyers** [comment]
It works for me, but maybe symlinks don't properly work in Windows? Does it work with `animation_spline/input.jxl`? (which should be the exact same file)

**Comment by vtorri** [comment]
there is no symlink (like unix symlink) on Windows.
animation_spline/input.jxl works, and is animated with my viewer

**Comment by vtorri** [comment]
indeed, animation_spline_5/input.jxl is 29 byes long. So git clone did something wrong

**Comment by vtorri** [comment]
ok, it's a sym link in git. Why having the same jxl file ?

**Comment by jonsneyers** [comment]
We have defined two levels of jxl conformance: level 5 and level 10 (more levels might be added later).

Level 10 is more strict than level 5 in terms of precision.

The conformance criteria are specified in terms of how much error is tolerated between the reference decoded images and your decoder's decoded images. Some jxl files are only used in level 10 (e.g. because they are encoded with a higher bitdepth than what you have to support for level 5), but most are used in both levels, just with a higher tolerance threshold in level 5 than in level 10. To avoid making the repo unnecessarily large, we did the duplicates with symlinks instead of copies.

It's somewhat annoying that Windows still does not have symlinks - it's a pretty useful feature :)

**Comment by vtorri** [comment]
symlink introduced in Vista can only be used in Administrator mode, so they are actually useless.

so, ok i close this invalid  issue,
